### ISSUE TITLE
eolearn.io S2L1CWCSInput issue

### ISSUE THREAD

**Issue by mahinkhankishizade** [sentinel-hub/sentinelhub-py#117]
Hello, 

Currently I am developing an API for crop classification, and I use S2L1CWCSInput for fetching sentinel data. It was working fine until last month. Now, when I try to create a S2L1CWCSInput object, I am getting the following error:

**During execution of task S2L1CWCSInput: index -1 is out of bounds for axis 0 with size 0**

This happens during this method:

<img width="448" alt="Screen Shot 2020-03-11 at 1 56 36 PM" src="https://user-images.githubusercontent.com/32219005/76410089-6c3bd880-63a0-11ea-99a4-bd16b45458fc.png">

Here, PRODUCT[name] is a layer name (NDVI for example). 
I would be really thankful if you explain the reasoning and if possible help me to devise a solution.

**Comment by batic** [comment]
Hi @mahinkhankishizade,

If this is still relevant, could you please provide a bit more info where this fails (e.g. stack trace)? The code snippet you pasted seems ok.

**Comment by mlubej** [comment]
Additionally, `S2L1CWCSInput` is deprecated, so please use `SentinelHubInputTask` from `eo-learn` and let us know if the issues persist.

Closing.
