### ISSUE TITLE
Error install sentinelhub

### ISSUE THREAD

**Issue by skemaikin** [sentinel-hub/sentinelhub-py#118]
Hello!
Docker + Ubuntu 18.04 + Python 3.7:

FROM ubuntu:18.04
RUN apt-get update && apt-get install -y software-properties-common python3.7 python3-pip
RUN pip3 install sentinelhub --upgrade

produces error:  
**imagecodecs/_aec.c:602:10: fatal error: libaec.h: No such file or directory  #include "libaec.h"
compilation terminated.**

Will be grateful for the help.
Sergey

**Comment by AleksMat** [comment]
Hi Sergey,

I think this happens during the installation `imagecodecs` package which is a dependency of `tifffile` package which is a dependency of `sentinelhub-py`.

My suggestion is that you first make sure that you have `gcc` (i.e. C++ compiler) installed in your docker. If this doesn't solve the problem, please check [here](https://pypi.org/project/imagecodecs/) for more info.

**Comment by skemaikin** [comment]
Hi Alex,

neither `gcc` no `imagecodecs` not improved the situation. I think this problem caused by the compatibility of new `sentilelhub-py` and `numpy`. Part of the log:

**/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    imagecodecs/_aec.c:602:10: fatal error: libaec.h: No such file or directory
     #include "libaec.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1**

Unfortunately, earlier version of `sentinel-py` does not solve the problem (((.

**Comment by batic** [comment]
apt-get install libaec-dev ?

**Comment by skemaikin** [comment]
Alex, libaec-dev solves this problem, but new problem occurred - with the blosc.h.
I solved blosc.h-problem with the help of the libblosc-dev, but a new one occurred - brotli\types.h. Anyway, each such solution causes a lot of warnings. I  don't like it (

**Comment by skemaikin** [comment]
SOLVED

The problem caused by the imagecodecs. Latest version requires newest ubuntu (19.10 +). Latest imagecodecs refuses to be installed on 18.10. At least, I can't install it on earlier ubuntu.

**Comment by skemaikin** [comment]
UPDATE

Having tested various options, I came to the conclusion that it was only my mistake. It is necessary to make sure that the `pip` version is the latest.
`pip install --upgrade pip` solved prolem.
