### ISSUE TITLE
AWSProductRequest Folder Structure

### ISSUE THREAD

**Issue by DShoemate** [sentinel-hub/sentinelhub-py#12]
Would it be possible to add the HTML, rep_info, and AUX_DATA folders to the downloaded product by default? They will be empty folders, but appear to be necessary for Sen2Cor 2.4.0 to start. If any of the three folders are missing the program will not run.

**Comment by AleksMat** [comment]
We have just released the version `1.0.2` where this issue is fixed. The empty folder are again being generated by default.

Thank you for letting us know about this. In version `1.0.0` we somehow thought those folders are irrelevant for any use case.
