### ISSUE TITLE
No response from sentinel hub service when tried to download numpy array from cube on EuroDataCube

### ISSUE THREAD

**Issue by shexiaogui** [sentinel-hub/sentinelhub-py#122]
I am a user of EuroDataCube under free trial plan. Today I experienced no response when I tried to download numpy array from a cube, or perform xarray operations like `.dropna()`
The cube looks like this. 

![image](https://user-images.githubusercontent.com/16511902/82551650-7d4f5580-9b58-11ea-816f-51971d895951.png)

Operations that hangs forever:

`cube.B03.values`
`cube = cube.dropna(dim='time',how="any")`

Is it because the plan's quota is reached ? Is there any way to check this ?

**Comment by gmilcinski** [comment]
You can check your available quota in the Configuration Utility:
https://apps.sentinel-hub.com/dashboard/#/
If you let me know your e-mail, we can bump you another set of processing units. If this really is the problem.

if you still have available quota, then we will need to get some more info on the error.

**Comment by shexiaogui** [comment]
We reached the limit and It was resolved just seconds ago. Thanks @gmilcinski
