### ISSUE TITLE
UtmGridSplitter and UtmZoneSplitter multiple UTM zones issue

### ISSUE THREAD

**Issue by dfnino10** [sentinel-hub/sentinelhub-py#123]
Hi,

I am using UtmZoneSplitter and UtmGridSplitter to divide a zone that spans across multiple UTM zones. I then create the bbox_list and bbox_list and having that I create the GeoDataFrame which I use for plotting. I am following this example [How To: Land-Use-Land-Cover Prediction for Slovenia](https://eo-learn.readthedocs.io/en/latest/examples/land-cover-map/SI_LULC_pipeline.html.). But when the plot is created it seems like the bboxes are divided into two groups. I have tested it in zones that do not span across multiple zones and it works perfectly.  

```
country = gpd.read_file(os.path.join(DATA_FOLDER, 'COLOMBIA.shp'))

depto = country[country.DPTO_CNMBR == "CASANARE"]

# Get the shape in polygon format
country_shape = country.geometry.values[-1]

depto_shape = depto.geometry.values[-1]

depto.plot()
plt.axis('off');
```

This shows the image below 

![Issue](https://user-images.githubusercontent.com/35967331/84573050-ca8fa300-ad63-11ea-9ab6-1b53cb9b379f.png)

Here is the part where I get the bbox_list and plot the bboxes
```
# Create the splitter to obtain a list of bboxes
bbox_splitter = UtmGridSplitter([depto_shape], CRS.WGS84, 5000)

bbox_list = np.array(bbox_splitter.get_bbox_list())
info_list = np.array(bbox_splitter.get_info_list())

# Prepare info of selected EOPatches
geometry = [Polygon(bbox.get_polygon()) for bbox in bbox_list]


idxs = [info['index'] for info in info_list]
idxs_x = [info['index_x'] for info in info_list]
idxs_y = [info['index_y'] for info in info_list]

gdf = gpd.GeoDataFrame({'index': idxs, 'index_x': idxs_x, 'index_y': idxs_y}, 
                           crs=country.crs, 
                           geometry=geometry)

# figure
fig, ax = plt.subplots(figsize=(30, 30))
gdf.plot(ax=ax,facecolor='w',edgecolor='r',alpha=0.5)
ax.set_title('Selected 5x5  tiles from Colombia', fontsize=30);
for bbox, info in zip(bbox_list, info_list):
    geo = bbox.geometry
    ax.text(geo.centroid.x, geo.centroid.y, info['index'], ha='center', va='center')
```
But this plots the image below.
![Issue1](https://user-images.githubusercontent.com/35967331/84573177-776a2000-ad64-11ea-927a-45f58cd1f250.png)

**Comment by devisperessutti** [comment]
Hi David,

In this case the splitter returns polygons over two UTM grids, which have different coordinate reference system (CRS). The issue arises when you put both sets into a single geopandas dataframe, which allows the definition of a single CRS. 

To correctly visualise the result you'd need to create two geopandas dataframes, one for each set of bboxes defined in their own CRS. The CRS is provided in the returned `info_list`, and it should be used to split the list into the two subsets to be correctly visualised with geopandas. When downloading images, there is no need to keep them separate as long as you provide the corresponding CRS to the UTM geometries.

Hope this helps,
Devis

**Comment by dfnino10** [comment]
Thank you for your answer. It's very helpful I thought the problem in the plotting was going to affect the downloading of the images. It seems it is not the case then. Thanks again.
