### ISSUE TITLE
Support for image download -  “[NEW] Pleiades - COVID19”

### ISSUE THREAD

**Issue by anma1980** [sentinel-hub/sentinelhub-py#124]
We are trying to download images from the data collection "[NEW] Pleiades - COVID19", using the SentinelHubRequest request but the process fails. Below we are sharing error received.
What could be the reason for this issue?
 
DownloadFailedException: Failed to download from:
https://services.sentinel-hub.com/api/v1/process
with HTTPError:
500 Server Error: Internal Server Error for url: https://services.sentinel-hub.com/api/v1/process
Server response: "{"error":{"status":500,"reason":"Internal Server Error","message":"java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Index service failure: 500 Internal Server Error","code":"RENDERER_EXCEPTION"}}"

The link reports the following:
{"error":{"status":405,"reason":"Method Not Allowed","message":"HTTP 405 Method Not Allowed","code":"COMMON_METHOD_NOT_ALLOWED"}}

Regards,

**Comment by gmilcinski** [comment]
Can you share your account's e-mail, so that we can check the logs?

**Comment by anma1980** [comment]
Hi,

The email is
Antonio.araujo@gmv.com<mailto:Antonio.araujo@gmv.com>

Thks

________________________________
[logo_gmv]

António Araújo
Gestor de Projeto e Negócio /
Project & Business Developer Manager /

GMV
Av. D. João II, Nº 43
Torre Fernão de Magalhães, 7º
1998-025 Lisboa
Tel. +351 21 382 93 66
Mob. +351 91 449 93 03
Fax +351 21 386 64 93
www.gmv.com<http://www.gmv.com/>
[facebook_XX]<http://www.facebook.com/infoGMV>

[twitter_24x30]<http://www.twitter.com/infoGMV_es>

[google-plus_24x30]<https://plus.google.com/+Gmvcompany>

[you-tube_24x30]<http://www.youtube.com/infoGMV>

[linked_24x30]<https://www.linkedin.com/company/gmv>

[rss_24x30]<http://www.gmv.com/en/RSS>


[GMV_blog_XX]<http://www.gmv.com/blog_gmv/language/en/>
