### ISSUE TITLE
Enable low resolution data access

### ISSUE THREAD

**Issue by mlubej** [sentinel-hub/sentinelhub-py#128]
In the [docs](https://docs.sentinel-hub.com/api/latest/#/data/Sentinel-2-L1C?id=previewmode) page it's stated that by default only resolutions to 250m area available. Would it make sense to add `previewMode: EXTENDED_PREVIEW` to the `SentinelHubRequest`? I noticed that I need to make the change here, since it's not possible to do it in `eo-learn.

**Comment by AleksMat** [comment]
This functionality is already possible with `SentinelHubRequest` class. You can pass `previewMode` to a parameter `other_args` of `input_data` method. More in [documentation](https://sentinelhub-py.readthedocs.io/en/latest/sentinelhub_request.html#sentinelhub.sentinelhub_request.SentinelHubRequest.input_data).

**Comment by mlubej** [comment]
> This functionality is already possible with `SentinelHubRequest` class. You can pass `previewMode` to a parameter `other_args` of `input_data` method. More in [documentation](https://sentinelhub-py.readthedocs.io/en/latest/sentinelhub_request.html#sentinelhub.sentinelhub_request.SentinelHubRequest.input_data).

I'm not sure that's correct, or I might not understand it correctly. I was aware of this parameter, but it didn't work the way I wanted it to.

Example here:

a) the original request

```javascript
{
  "bounds":{
    "bbox":[
      46.16,
      -16.15,
      46.51,
      -15.58
    ],
    "properties":{
      "crs":"http://www.opengis.net/def/crs/EPSG/0/4326"
    }
  },
  "data":[
    {
      "dataFilter":{
        "maxCloudCoverage":100,
        "mosaickingOrder":"mostRecent",
        "timeRange":{
          "from":"2020-06-12T00:00:00Z",
          "to":"2020-06-13T23:59:59Z"
        }
      },
      "type":"S2L1C"
    }
  ]
}
```

If I add `other_args = {'previewMode': 'EXTENDED_PREVIEW'}` I get

```javascript
{
  "bounds":{
    "bbox":[
      46.16,
      -16.15,
      46.51,
      -15.58
    ],
    "properties":{
      "crs":"http://www.opengis.net/def/crs/EPSG/0/4326"
    }
  },
  "data":[
    {
      "dataFilter":{
        "maxCloudCoverage":100,
        "mosaickingOrder":"mostRecent",
        "timeRange":{
          "from":"2020-06-12T00:00:00Z",
          "to":"2020-06-13T23:59:59Z"
        }
      },
      "previewMode":"EXTENDED_PREVIEW",
      "type":"S2L1C"
    }
  ]
}
```

and you can see that the `previewMode` is in the wrong position, so I can add the nested one `other_args = {'dataFilter': {'previewMode': 'EXTENDED_PREVIEW'}}`

```javascript
{
  "bounds":{
    "bbox":[
      46.16,
      -16.15,
      46.51,
      -15.58
    ],
    "properties":{
      "crs":"http://www.opengis.net/def/crs/EPSG/0/4326"
    }
  },
  "data":[
    {
      "dataFilter":{
        "maxCloudCoverage":100,
        "mosaickingOrder":"mostRecent",
        "timeRange":{
          "from":"2020-06-12T00:00:00Z",
          "to":"2020-06-13T23:59:59Z"
        }
      },
      "type":"S2L1C"
    }
  ]
}
```

but in this case, the whole `dataFilter` fields gets overridden.

Is this the expected behaviour?

**Comment by mlubej** [comment]
In any case, of course, there are workarounds, I just wanted to suggest to add this to the request since it doesn't really change the existing functionality anyways. EOBrowser works in the same way, iirc.

**Comment by mlubej** [comment]
Fixed in SH, now it needs to be exposed in `eolearn`
