### ISSUE TITLE
how to extract rooftop images using sentinel-2

### ISSUE THREAD

**Issue by amoozmand** [sentinel-hub/sentinelhub-py#129]
I am writing to ask for how to extract images of rooftops using sentinel 2. preferably by python API.

Thank you

**Comment by mlubej** [comment]
Hi @amoozmand 

With this package, you are able to download the images with which you might be able to tackle the task which you mention. How you do that is then out of scope of this package.

Essentially you would need to do some GIS tasks and extract the pixels which fall on the same area as your rooftop vector data.

Good luck!
