### ISSUE TITLE
AwsProductRequest().get_data () causing python to crash

### ISSUE THREAD

**Issue by spatialtrail** [sentinel-hub/sentinelhub-py#13]
Hi,

I am following through the aws_request examples but keep getting python crashes with request.get_data(). Request.save_data() runs successfully and the expected data is downloaded but upon calling request.get_data() python crashes:

```
from sentinelhub.data_request import AwsProductRequest
product_id = 'S2A_MSIL1C_20171010T003621_N0205_R002_T01WCV_20171010T003615'
data_folder = 'C:/path/to/folder'

request = AwsProductRequest(product_id=product_id, data_folder=data_folder)
data_list = request.get_data(save_data=False,redownload=True)
```

![image](https://user-images.githubusercontent.com/13465873/35384603-c3f3bc10-01bd-11e8-97a5-7520ea520bf2.png)

Issue is different when specifying the data_folder relatively, python does not crash but request.get_data() errors out:
`data_folder = '.'`

![sentinelhub-py_issue](https://user-images.githubusercontent.com/13465873/35385285-b7b64e48-01bf-11e8-80ad-1f2be18d1428.PNG)

conda 4.3.3
python 3.6

Any ideas where I am going wrong or might this be a bug?

**Comment by spatialtrail** [comment]
Pip installing sentinelhub had installed glymur version 0.8.14. I just reinstalled glymur (version 0.8.12) with conda and then reinstalled sentinelhub and my issues seem to be fixed (data_list now returns a list of numpy arrays as expected)!

**Comment by AleksMat** [comment]
Hello,

the problem you are facing is the one we haven't completely solved it ourselves. For now we don't know how to correctly decode `jp2` data without first saving them.

So the quick solution is to first save data with either `request.save_data()` method or `request.get_data(save_data=True)` method. You might also want to leave `redownload` flag to `False`. That will allow you that next time you call `request.get_data()` the data will be read from disk and not downloaded again. So this should work:
```Python
from sentinelhub.data_request import AwsProductRequest
product_id = 'S2A_MSIL1C_20171010T003621_N0205_R002_T01WCV_20171010T003615'
data_folder = 'C:/path/to/folder'

request = AwsProductRequest(product_id=product_id, data_folder=data_folder)
data_list = request.get_data(save_data=True)
```
About the folder path I believe it should work if you specify either relative or absolute path.

**Comment by AleksMat** [comment]
I see there are problems with running the latest version of glymur in conda environment. We will change package dependencies to use glymur version 0.8.12. Thanks for letting us know about this.

**Comment by AleksMat** [comment]
In new version `1.0.4` the package now installs `glymur` version `0.8.12`
