### ISSUE TITLE
Large area utilities - ValueError: 'vertices' must be a 2D list or array with shape Nx2

### ISSUE THREAD

**Issue by VJ-sts** [sentinel-hub/sentinelhub-py#131]
Hi
I am trying to split the area of the larger polygon. 

When I run 

_show_splitter(bbox_splitter, show_legend=True)_

I am getting the following error.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-4c071552cdbb> in <module>
      1 bbox_splitter_reduced = BBoxSplitter([Multi], CRS.WGS84, (5, 4), reduce_bbox_sizes=True)
      2 
----> 3 show_splitter(bbox_splitter_reduced, show_legend=True)

<ipython-input-29-c5113b556610> in show_splitter(splitter, alpha, area_buffer, show_legend)
     14     base_map = Basemap(projection='mill', lat_0=lat, lon_0=lng, llcrnrlon=minx, llcrnrlat=miny,
     15                        urcrnrlon=maxx, urcrnrlat=maxy, resolution='l', epsg=4326)
---> 16     base_map.drawcoastlines(color=(0, 0, 0, 0))
     17 
     18     area_shape = splitter.get_area_shape()

C:\Anaconda\envs\gdal\lib\site-packages\mpl_toolkits\basemap\__init__.py in drawcoastlines(self, linewidth, linestyle, color, antialiased, ax, zorder)
   1844         # get current axes instance (if none specified).
   1845         ax = ax or self._check_ax()
-> 1846         coastlines = LineCollection(self.coastsegs,antialiaseds=(antialiased,))
   1847         coastlines.set_color(color)
   1848         coastlines.set_linestyle(linestyle)

C:\Anaconda\envs\gdal\lib\site-packages\matplotlib\collections.py in __init__(self, segments, linewidths, colors, antialiaseds, linestyles, offsets, transOffset, norm, cmap, pickradius, zorder, facecolors, **kwargs)
   1357             **kwargs)
   1358 
-> 1359         self.set_segments(segments)
   1360 
   1361     def set_segments(self, segments):

C:\Anaconda\envs\gdal\lib\site-packages\matplotlib\collections.py in set_segments(self, segments)
   1372             _segments = self._add_offsets(_segments)
   1373 
-> 1374         self._paths = [mpath.Path(_seg) for _seg in _segments]
   1375         self.stale = True
   1376 

C:\Anaconda\envs\gdal\lib\site-packages\matplotlib\collections.py in <listcomp>(.0)
   1372             _segments = self._add_offsets(_segments)
   1373 
-> 1374         self._paths = [mpath.Path(_seg) for _seg in _segments]
   1375         self.stale = True
   1376 

C:\Anaconda\envs\gdal\lib\site-packages\matplotlib\path.py in __init__(self, vertices, codes, _interpolation_steps, closed, readonly)
    128         if vertices.ndim != 2 or vertices.shape[1] != 2:
    129             raise ValueError(
--> 130                 "'vertices' must be a 2D list or array with shape Nx2")
    131 
    132         if codes is not None:

**ValueError: 'vertices' must be a 2D list or array with shape Nx2**

​

**Comment by AleksMat** [comment]
Hi @VJ-sts,

My guess would be that your versions of `basemap` and `matplotlib` are not compatible. I suggest checking their versions and which versions you get if you install them with conda or pip.

Since `basemap` is deprecated we will eventually have to replace it with `cartopy` or maybe `geopandas`. But because we use it only in those notebook examples and it is not a dependency of sentinelhub-py package it is, for now, a low priority.
