### ISSUE TITLE
[NEW] [NEW] Deimos - COVID19

### ISSUE THREAD

**Issue by anma1980** [sentinel-hub/sentinelhub-py#133]
Dear team

We are trying to download images from the data collection "[NEW] [NEW] Deimos", using the SentinelHubRequest request but the process fails. Below we are sharing the error received.

DownloadFailedException: Failed to download from:
https://services.sentinel-hub.com/api/v1/process
with HTTPError:
404 Client Error: Not Found for url: https://services.sentinel-hub.com/api/v1/process
Server response: "{"error":{"status":404,"reason":"Not Found","message":"BYOC collection bexxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx6f not found.","code":"COMMON_NOT_FOUND"}}"

Using the same procedure, we are able to download other images from other collections in the same AOI. In the sentinel-hub dashboard we confirmed the correct ID and BYOC number. Any clue why are we getting this error?

Regards,

**Comment by gmilcinski** [comment]
Dear @anma1980 ,

Deimos collection is hosted on Mundi Web Services, so you need to use different end-point.
instead of 
https://services.sentinel-hub.com/api/v1/process
you have to use
https:shservices.mundiwebservices.com/api/v1/process
