### ISSUE TITLE
no data returned for bbox using my own coordinates

### ISSUE THREAD

**Issue by MinXu1991** [sentinel-hub/sentinelhub-py#134]
I am using bbox to download Sentinel-2 L1C data for this area [28.76, -81.95, 28.81, -81.89] but get no data returned. If using the coordinates in the example, it works well. But it did not work for my coordinates. Any help is much appreciated. My codes are shown below:

from sentinelhub import SHConfig

INSTANCE_ID = 'my instance ID'

if INSTANCE_ID:
    config = SHConfig()
    config.instance_id = INSTANCE_ID
else:
    config = None

from sentinelhub import CRS, BBox, MimeType, WcsRequest

#ROI_coords_wgs84 = [46.26, -16.05, 46.51, -15.58], worked using this one or coordinates in the example, 
# but not for the one below
ROI_coords_wgs84 = [28.76, -81.95, 28.81, -81.89]
search_bbox = BBox(bbox=ROI_coords_wgs84, crs=CRS.WGS84)

wcs_bands_request = WcsRequest(
    data_folder='C://test_dir_S2',
    layer='BANDS-S2-L1C',
    bbox=search_bbox,
    time=('2019-01-01', '2019-02-01'),
    image_format=MimeType.TIFF_d32f,
    resx='60m',
    resy='60m',
    config=config
)

wcs_bands_img = wcs_bands_request.get_data(save_data=True)
print(len(wcs_bands_img))

**Comment by AleksMat** [comment]
Hi @MinXu1991,

Please note that the coordinate order should be longitude-latitude and not latitude-longitude. The bounding box you are currently requesting is located in the middle of Antarctica and therefore there might not be any images available for that area.

**Comment by MinXu1991** [comment]
Thank you so much! That solved my problem.
