### ISSUE TITLE
Support Batch Process API

### ISSUE THREAD

**Issue by CloudNiner** [sentinel-hub/sentinelhub-py#136]
Hi! We're using the [Batch Process API](https://docs.sentinel-hub.com/api/latest/api/batch/) that's currently in beta. Is this an API that you would eventually want to see helpers for in this library, or would that belong elsewhere?

**Comment by AleksMat** [comment]
The batch interface in `sentinelhub-py` has been added in the newly released version `3.1.0`. A tutorial about it is available [here](https://sentinelhub-py.readthedocs.io/en/latest/examples/batch_processing.html).

Feel free to submit a pull request with any additional features that might be missing in the current implementation.
