### ISSUE TITLE
[HELP] How could I validate the algorithm?

### ISSUE THREAD

**Issue by JK-Pair** [sentinel-hub/sentinelhub-py#150]

**Comment by AleksMat** [comment]
Hi @JK-Pair,

You will have to provide much more information about your problem.

**Comment by JK-Pair** [comment]
> Hi @JK-Pair,
> 
> You will have to provide much more information about your problem.

I'm sorry for the unclear question

I mean if I want to compare this algorithm with another algorithm, How could I do that?

Maybe you could suggest some blog about this to me?

**Comment by AleksMat** [comment]
This is still too general question and not related to sentinelhub-py.

Feel free to read some blog bost about the work we do with satellite data: https://medium.com/sentinel-hub
