### ISSUE TITLE
services.sentinel-hub.com 503 Service Unavailable

### ISSUE THREAD

**Issue by makaay2077** [sentinel-hub/sentinelhub-py#152]
I am getting an error message beacuse "https://services.sentinel-hub.com/" 503 Service Unavailable

**Comment by gmilcinski** [comment]
Can you be more specific on what you are doing to get this error? Is it repeatitive or just occasional?
We do not see anything specific on the back-end, things are working nominally.

Note that 503 error here and there is expected with such level of processing, so you need to take it into account when designing your procedures, e.g. performing a retry a few times before gaving up.
