### ISSUE TITLE
[BUG] Visual tracking tool plots incorrectly with projection other than EPSG:4326

### ISSUE THREAD

**Issue by chorng** [sentinel-hub/sentinelhub-py#153]
When you used the `plot_batch_splitter` function as described in the [documentation](https://sentinelhub-py.readthedocs.io/en/latest/examples/batch_processing.html#) with an other projection than EPSG:4326, the function doesn't plot correctly because ```get_bbox_list``` function will convert splitter's coordinates to EPSG:4326 as its return but ```crs.pyproj_crs``` will get the origin crs of splitter and set it as the crs of gdf. Consequently, the function is plotting EPSG:4326 coordinates value on another crs plane, in this case the EPSG:3035.

Input:
```python
def plot_batch_splitter_bug(splitter):
    gdf = gpd.GeoDataFrame({
        'status': [info['status'] for info in splitter.get_info_list()],
        'geometry': splitter.get_bbox_list()
    }, crs=splitter.crs.pyproj_crs())
    print('gdf coords with splitter.get_bbox_list(): ', gdf['geometry'][0])
    print('gdf crs: ', gdf.crs)
    ax = gdf.plot(column='status', legend=True, figsize=(10, 10))

    area_series = gpd.GeoSeries(
        [splitter.get_area_shape()],
        crs=splitter.crs.pyproj_crs()
    )
    
    area_series.plot(ax=ax, facecolor='none', edgecolor='black')

splitter = BatchSplitter(batch_request=batch_request)

plot_batch_splitter_bug(splitter)
```

Output:
<img width="984" alt="Screen Shot 2021-01-25 at 6 58 35 PM" src="https://user-images.githubusercontent.com/78031577/105858480-a67b8c00-5feb-11eb-8af2-bbda1f612de3.png">

To make the tool works, the crs of gdf needs to be specified as "EPSG:4326" and then apply ```gdf.to_crs(splitter.crs.pyproj_crs())``` to convert the gdf to the correct crs as shown below:

Input:
```python
def plot_batch_splitter(splitter):
    gdf = gpd.GeoDataFrame({
        'status': [info['status'] for info in splitter.get_info_list()],
        'geometry': splitter.get_bbox_list()
    }, crs="EPSG:4326")
    
    gdf = gdf.to_crs(splitter.crs.pyproj_crs())
    
    ax = gdf.plot(column='status', legend=True, figsize=(10, 10))

    area_series = gpd.GeoSeries(
        [splitter.get_area_shape()],
        crs=splitter.crs.pyproj_crs()
    )
    
    area_series.plot(ax=ax, facecolor='none', edgecolor='black')
```

**Environment:**

Python 3

**Desktop:**

 - OS: macOS 11.1
 - Browser: chrome

**Comment by AleksMat** [comment]
In the new package version `3.4.0` we made changes of `BatchSplitter` class and fixed `plot_batch_splitter` function. The function will now always transform bounding boxes into a CRS of the input area of interest.
