### ISSUE TITLE
[FEAT] Return path to saved data from SentinelHubRequest

### ISSUE THREAD

**Issue by ghost** [sentinel-hub/sentinelhub-py#163]
It would be nice if we could get the path to saved data from a SentinelHubRequest.

Something like this would work:

request = SentinelHubRequest(evalscript, input_data, ...)
path_to_saved_data = request.save_data()

**Comment by AleksMat** [comment]
Hi @juansensio,

There is a method `SentinelHubRequest.get_filename_list` that returns a list of paths relative to `data_folder`. You can do

```Python
request = SentinelHubRequest(evalscript, input_data, ...)
request.get_filename_list()
```

Would this method be enough?
