### ISSUE TITLE
[HELP] extremely slow downloading a directory from S3

### ISSUE THREAD

**Issue by mauroc** [sentinel-hub/sentinelhub-py#168]
I am experimenting with sentinelhub but it's taking forever to download a SAFE directory

```
# python --version -> Python 3.6.9
sentinelhub.__version__ -> '3.1.0'

from sentinelhub import AwsProductRequest
product_id = 'S2B_MSIL2A_20190513T162839_N0212_R083_T16RBU_20190513T221002'
request = AwsProductRequest(product_id=product_id, data_folder=Dest_dir, safe_format=True)
data_list = request.get_data(save_data=True)
```
the last command takes over 12 minutes, vs. about 12 secs when I download the zipped version of the same product using boto3 (unfortunately the `sentinel-s2-l2a-zips` bucket only includes a rolling 2-week's worth of products). 

What am I doing wrong?

**Comment by AleksMat** [comment]
Hi @mauroc,

I think reading JP2 files into memory is actually the slow part here. If you just want to download data and not load it into memory I recommend replacing the line

```Python
data_list = request.get_data(save_data=True)
```
with
```Python
request.save_data()
```

I tried running with this change and it took 2 minutes and 50 seconds (my bandwidth is also not very good). Both `save_data` and `get_data` methods also have a parameter `max_threads` to specify how many parallel threads will be used for download. By default, the number is already quite high (5-times the number of your CPUs) but you can try increasing it even further.

I hope this helps.

**Comment by mauroc** [comment]
@AleksMat 
that worked! 15.5 secs (from S3 to a DigitalOcean instance).
Thank you so much for the quick response
