### ISSUE TITLE
[FEAT] Explicit setting of tile id for the Batch processing API

### ISSUE THREAD

**Issue by gakarak** [sentinel-hub/sentinelhub-py#170]
**What is the problem? Please describe.**

I want to explicitly specify the **tile identifiers** (tile id) instead of setting the region geometry in the **Python Batch Processing API** (as I understand it in the REST API the same thing) to setup the region for data processing.

**What i tried to do**

I want to download raw Senitnel1 (orthirectified, sigma0) & Sentinel2 (L1C) timed data. For this I am using a grid to slice the data. Since the data for Sentinel-Hub is prepared according to one of the GRIDs [(tiling-grids),](https://docs.sentinel-hub.com/api/latest/api/batch/#tiling-grids) I decided to use the grid from **sentinelhub**.

Since I want to download data sliced by dates, I first select those tiles for which there is data for a certain date. Then I would like to download the tiles after selecting them. However, all selected tiles combined into one multipolygon cannot be given as geometry for downloading (**geometry** parameter in **SeninelHubRequest**) due to the constraint on geometry complexity. I would like to explicitly pass the **Tiles IDs** of the tiles to which I want to crawl the data (and independently control their selection), instead of implicitly specifying them through geometry.

**Comment by gmilcinski** [comment]
There is no option to specify tile ID to Batch Processing API. I do not understand your use-case really. There is no need to "search where data are available" as this can be done by Batch API as well.  
You can simply select the AOI of choice and then configure the Batch Processing API request so that you will get outputs for individual observations.

**Comment by gakarak** [comment]
is there somewhere an example of how to save individual dates into separate files using the Batch Processing API?
Those. I would like to download the data in the format:
`$ROOT_DIR/<grid_id>/date_for_grid/VV.tif`
for every individual date available for grid cells

In the examples, I found only:
-  data averaging over a range of dates (as it is done in the script [interpolation_evalscript.js](https://github.com/sentinel-hub/sentinelhub-py/blob/master/examples/data/interpolation_evalscript.js) )
- aggregate each individual date for every bad in multichannel GeoTIF [data_evalscript.js](https://github.com/sentinel-hub/field-delineation/blob/main/fd/evalscripts/data_evalscript.js)

But I have not found an easy way to download in **grid regions** into separate files for each date :(


Maybe I really didn't find a solution and started solving the problem incorrectly.

**Comment by gmilcinski** [comment]
To do what what you want, you would need to pre-define "outputs" for each date, but this might be a bit clunky.
There are two options I see at the moment:
1) You simply call your request for each individual day, but for a whole region (e.g. whole continent, if you like). You will only be charged for tiles, which do actually contain any data. 
2) To use the request along the lines attached below. This will produce N-band GeoTiffs, where each "band" will represent one observation, and a JSON meta-data with information on observation dates. We recommend to run such a request for a monthly period, e.g. one for each month. 

Request: 
```
{
  "processRequest": {
    "input": {
      "bounds": {
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
                [
              8.294677734375,
              41.31082388091818
            ],
            [
              10.04150390625,
              41.31082388091818
            ],
            [
              10.04150390625,
              43.23719944365308
            ],
            [
              8.294677734375,
              43.23719944365308
            ],
            [
              8.294677734375,
              41.31082388091818
            ]
            ]
          ]
        },
        "properties": {
          "crs": "http://www.opengis.net/def/crs/EPSG/0/4326"
        }
      },
      "data": [
        {
          "type": "S1GRD",
          "dataFilter": {
            "timeRange": {
              "from": "2018-06-01T00:00:00Z",
              "to": "2018-07-01T00:00:00Z"
            },
            "mosaickingOrder": "mostRecent",
            "maxCloudCoverage": 100,
            "resolution": "HIGH",
            "acquisitionMode": "IW",
            "polarization": "DV",
            "orbitDirection": "ASCENDING"
          },
          "processing": {
            "backCoeff": "GAMMA0_TERRAIN",
            "orthorectify": true,
            "demInstance": "COPERNICUS"
          }
        }
      ]
    },
    "output": {
      "responses": [
        {
          "identifier": "VVdB",
          "format": {
            "type": "image/tiff"
          }
        },
        {
          "identifier": "VHdB",
          "format": {
            "type": "image/tiff"
          }
        },
        {
          "identifier": "userdata",
          "format": {
            "type": "application/json"
          }
        }
      ]
    }
  },
  "tilingGrid": {
    "id": 0,
    "resolution": 10
  },
  "output": {
    "defaultTilePath": "s3://<S3_BUCKET_NAME>/<requestId>/<tileName>_<outputId>.<format>"
  },
  "description": "S1 batch 2018 06"
}
```

EVALSCRIPT: 
```
//VERSION=3

function setup() {
    return {
      input: ["VV", "VH"],
      output: [
          {id: "VVdB", bands: 1, sampleType: SampleType.FLOAT32},
          {id: "VHdB", bands: 1, sampleType: SampleType.FLOAT32}
      ],
      mosaicking: Mosaicking.ORBIT
    }
  }
  
  function updateOutput(outputs, collection) {
    Object.values(outputs).forEach((output) => {
        output.bands = collection.scenes.length;
    });
  }

  function updateOutputMetadata(scenes, inputMetadata, outputMetadata) {
    var dds = [];
    for (i=0; i<scenes.length; i++){
      dds.push(scenes[i].date)
    }
    outputMetadata.userData = { "acquisition_dates":  JSON.stringify(dds) }
  }
  
  function toDb(linear) {
    // the following commented out lines are simplified below
    return 10 * Math.log(linear) / Math.LN10
  }

  function evaluatePixel(samples) {
    var n_observations = samples.length
    
    let array_vv = new Array(n_observations).fill(0)
    let array_vh = new Array(n_observations).fill(0)
    
    samples.forEach((sample, index) => {
        array_vv[index] = toDb(sample.VV)
        array_vh[index] = toDb(sample.VH)
    });
    
    return {
        VVdB: array_vv,
        VHdB: array_vh,
    }
  }

```

**Comment by gakarak** [comment]
The second option (to save all dates for each band in a separate multichannel-tif) is very inconvenient for me, since I want to download constantly up-to-date data (all actual data every day).

The first option seems to be ok, if the fee for empty areas is not really taken. But in this case, only data tiles will be recorded on the **s3-storage**, or all?

**Comment by gmilcinski** [comment]
It depends quite a bit on your EVALSCRIPT, there might be some files, e.g. metadata, etc.  
Make sure to use mosaicking=ORBIT. 

If you want to be super efficient, I suggest you check how it is done in S1 CARD4L application. Here the application (process) checks for the available data and performs the requests based on data takes:  
https://apps.sentinel-hub.com/s1-card4l/

**Comment by AleksMat** [comment]
Closing the issue. Feel free to reopen for any further questions.
