### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by gakarak** [sentinel-hub/sentinelhub-py#171]
Is there a way to directly download **Sentinel1** data sliced by tiling grids (data that available for **Batch Processing API**)?
I know there is a bucket (**sentinel-s1-l1c**) but there is data without DEM **Orthorectification**.

**Comment by gmilcinski** [comment]
Just to be clear - there are no "data available" - the data are processed on demand, when you trigger Batch Processing API. To do that, you need to provide AWS S3 bucket, where products will be delivered. Once on the bucket, you can use "aws sync" CLI tool to download.
