### ISSUE TITLE
[BUG] cannot import name 'SentinelHubCatalog' from 'sentinelhub' (/lib/python3.7/site-packages/sentinelhub/__init__.py)

### ISSUE THREAD

**Issue by Lotus08** [sentinel-hub/sentinelhub-py#177]
**Describe the bug**

When you do `conda install -c conda-forge sentinelhub ` and import SentinelHubCatalog, it throws `cannot import name 'SentinelHubCatalog' from 'sentinelhub' ` error. It does not happen if you do a pip install. I looked at the __init__.py in my env and it looks like SentinelHubCatalog class was not imported.

**Comment by AleksMat** [comment]
Hi @Lotus08,

The newest version of `sentinelhub` package is available via pip while conda-forge still has an older version. If you are using `sentinelhub` with conda I recommend first installing with conda and then upgrading version with pip.

**Comment by Lotus08** [comment]
ok, thanks
