### ISSUE TITLE
Problems during Installation - failed to build tiffile

### ISSUE THREAD

**Issue by mdoubko** [sentinel-hub/sentinelhub-py#18]
![error_sentinelhub](https://user-images.githubusercontent.com/35879970/35477130-175351f8-03bd-11e8-9018-ca86623853fd.png)
Sorry, I am relatively new to installing packages with pip and python. While installing Sentinelhub I could not get through the error related to installation of tiffle (see attachement). Any tips? Thanks.

**Comment by AleksMat** [comment]
Hi mdoubko,

some Python packages such as `tifffile` have modules written in C and therefore require a C compiler. On Windows such compiler is provided by Visual Studio. Therefore it seems that you either don't have a C compiler installed or it is outdated.

One solution should be to install the latest version of Visual Studio. For more about this problem please check here: https://stackoverflow.com/questions/29846087/microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat

**Comment by mdoubko** [comment]
Thanks a lot AleksMat,

I always try to avoid installation of Visual Studio unless neccessary. In this case, installing a custom version for Windows10 solved this problem.
Marcela
