### ISSUE TITLE
AttributeError: UTM_*

### ISSUE THREAD

**Issue by mdoubko** [sentinel-hub/sentinelhub-py#19]
In a following script AtributeError for UTM_33 appears not able to read this atribute. Am I using a correct CRS name? I adjusted it according to: http://sentinelhub-py.readthedocs.io/en/latest/common.html#sentinelhub.common.BBox.

betsiboka_coords_utm = [545461.852, 5223143.25, 548510.849, 5225341.7800]
betsiboka_bbox = BBox(bbox=betsiboka_coords_utm,crs=CRS.UTM_33)

wcs_true_color_request = WcsRequest(data_folder='C:\DATA_raw\Sentinel2_WCScalls\data\Mitterdorf_32633_atm_testSentinelhubpython',
                                    source=DataSource.WCS,                               
                                    layer='B04',                             
                                    bbox=betsiboka_bbox,
                                    time=('2017-12-01','2017-12-31'),
                                    image_format=MimeType.TIFF_d32f,
                                    instance_id=userID)

wcs_true_color_img = wcs_true_color_request.get_data(save_data=True)

**Comment by AleksMat** [comment]
In the UTM crs name you also have to specify the hemisphere - north or south. So your crs should be either `CRS.UTM_33N` or `CRS.UTM_33S`.

In the future you can check the list of all available crs with:
```python
from sentinelhub import CRS

dir(CRS)
```

**Comment by mdoubko** [comment]
thanks a lot for a great support
