### ISSUE TITLE
Sentinel-1 EW orthorectification using the SentinelHubRequest method

### ISSUE THREAD

**Issue by AdrienWehrle** [sentinel-hub/sentinelhub-py#192]
Hi all, 

I am currently trying to download orthorectified Sentinel-1 EW images using the `SentinelHubRequest` method. Unfortunately, after some intensive research in the source code and the documentation, I still can not find how to enable the orthorectification for `SentinelHubRequest`. I only found some examples for `WmsRequest`. From the source code, I thought the way to go was to use the `other_args` argument and pass the dictionary `{"orthorectify": True}`, but that does not help unfortunately.

Here is a short example of request (including the attempt with `other_args`, and `data_folder` being a local path, `config` my `sentinelhub.config.SHConfig`):

```python
evalscript = """
    //VERSION=3

    return [HH, dataMask]
"""

loc_bbox = BBox(bbox=[-50.5, 69.71, -49.5, 69.97], crs=CRS.WGS84)
loc_size = bbox_to_dimensions(loc_bbox, resolution=50)

request_all_bands = SentinelHubRequest(
    data_folder=data_folder,
    evalscript=evalscript,
    input_data=[
        SentinelHubRequest.input_data(
            data_collection=DataCollection.SENTINEL1_EW,
            time_interval=("2020-07-02", "2020-07-30"),
            other_args={"orthorectify": True},
        )
    ],
    responses=[SentinelHubRequest.output_response("default", MimeType.TIFF),],
    bbox=loc_bbox,
    size=loc_size,
    config=config,
)

outputs = request_all_bands.get_data()
```

Thank you a lot in advance for your help!

**Comment by AleksMat** [comment]
Hi @AdrienWehrle,

You were very close to the correct solution, which is to set:

```python
other_args={
    "processing": {
        "orthorectify": True
    }
}
```

This design is trying to somewhat follow the official [Process API docs](https://docs.sentinel-hub.com/api/latest/reference/#operation/process) where you also have nesting `input` -> `data` -> `processing` -> `orthorectify`.

**Comment by AdrienWehrle** [comment]
> Hi @AdrienWehrle,
> 
> You were very close to the correct solution, which is to set:
> 
> ```python
> other_args={
>     "processing": {
>         "orthorectify": True
>     }
> }
> ```
> 
> This design is trying to somewhat follow the official [Process API docs](https://docs.sentinel-hub.com/api/latest/reference/#operation/process) where you also have nesting `input` -> `data` -> `processing` -> `orthorectify`.

Thank you a lot! It could be interesting to add this argument to one of the nice examples of `SentinelHubRequest`!
