### ISSUE TITLE
[BUG] Wrong Granule naming for Sentinel 2 reprocessed products in SAFE format 

### ISSUE THREAD

**Issue by marcosdejesus** [sentinel-hub/sentinelhub-py#194]
**Describe the bug**

Some Sentinel 2 reprocessed products(baseline 00.01) have the wrong Granule name, in comparison to what is shown on the Metadata files, when dowloaded in SAFE format 

**To Reproduce**

1. Download product S2B_MSIL2A_20181119T172619_N0001_R012_T14SPG_20200916T182702 using sentinelhub-py in SAFE format
2. Compare the name of the folder inside S2B_MSIL2A_20181119T172619_N0001_R012_T14SPG_20200916T182702.SAFE/GRANULE/ to what name on manisfest.safe

**Expected behavior**

I would expect the granule folder to be named L2A_T14SPG_A008904_20181119T172945, but it is named L2A_T14SPG_A008904_20181119T173319

**Stack trace or screenshots**

Granule Name:
![Screen Shot 2021-08-31 at 1 20 31 PM](https://user-images.githubusercontent.com/22627006/131570594-4510a63f-34fc-4468-90c7-6942b654b070.png)
manifest.safe:
![Screen Shot 2021-08-31 at 1 21 35 PM](https://user-images.githubusercontent.com/22627006/131570606-e294f8e8-afe7-4045-90ec-5fda6a993769.png)

**Additional context**

I know why this problem is happening and I am mostly looking for some guidance on how to fix it.

The problem is happening because of this section of the code
https://github.com/sentinel-hub/sentinelhub-py/blob/d3b74201cbb613f6866e75e19527339967b9a2e1/sentinelhub/aws_safe.py#L275-L279

Considering that we are talking about L2A products, what happens is that the reprocessed products have more than one baseline internally, 02.10 and 02.09, but it is always trying create the tile id using the sensing time when it is supposed to use the datastrip time on products like the one showed above.

My problem is that what is called tile_id_time on the code is called 'Tile Discriminator' on ESA Sentinel 2 Product Specification, but there is no explanation about how it is formed. Because of that I am having a hard time figuring out a way to recreate it.

**Comment by AleksMat** [comment]
I see that the problem is that we don't know if switching from sensing to a datastrip time, when creating tile id, is always correct for baseline 00.01. (Our process of reconstruction also doesn't look at the info from manifest to determine that.)

For now we only have examples where using datastrip time is the correct solution. Therefore I switched to datastip time in https://github.com/sentinel-hub/sentinelhub-py/pull/244. If ever a counter example appears then we'll have to make a more sophisticated logic.

**Comment by marcosdejesus** [comment]
Thanks for the fix @AleksMat. I think that using the datastrip time should solve the problem.

Thanks for adding test cases using products with baseline 00.01 on https://github.com/sentinel-hub/sentinelhub-py/pull/243.
