### ISSUE TITLE
WCS request with time range writes empty images

### ISSUE THREAD

**Issue by schmidGV** [sentinel-hub/sentinelhub-py#20]
The following code example shows a WCS request, which should automatically save tiff-images of a specific bounding box (mybbox) and time range. The Layer is called 'NDVI' in my Configurater Utility.

```
mybbox = [47.24, 11.05, 47.61, 11.55]    
BBOX = BBox(bbox=mybbox, crs=CRS.WGS84)

wcs = WcsRequest(data_folder=outdir,
                              layer='NDVI',
                              bbox=BBOX,
                              time=('2017-08-15', '2017-08-25'),
                              resx='20m', resy='20m',
                              image_format=MimeType.TIFF_d32f,
                              instance_id=INSTANCE_ID)

wcs_img = wcs.get_data(save_data=True)
```

The NDVI images are completely downloaded. However, only 3 from 5 images have a content, while the other 2 are empty. Because it is a time range and I get no error message, what is the most convenient way to avoid that issue. I also tried `wcs.get_data(redownload=True)`, but this did not solve the problem.

**Comment by blazs** [comment]
Hi,

we have tried running your code snippet and all five images look just fine.

Can you try adding
`logging.basicConfig(filename='example.log',level=logging.DEBUG)`
to your code and show us the logging output?

**Comment by schmidGV** [comment]
I do not get any helpful information from the logs

![grafik](https://user-images.githubusercontent.com/17953642/35740558-717903f4-0835-11e8-9865-065938c28fb5.png)

**Comment by blazs** [comment]
Alright. We will need more information in order to help.

Could you perhaps upload a self-containing snippet that reproduces the issue as well as all of the outputs that you receive?

If you defined the `NDVI` layer in the WMS Configurator yourself then please also send the configurations.
 
In case it turns out to be configuration-related problem we can take this discussion off public thread and continue over email (blaz.sovdat@sinergise.com).

**Comment by mkadunc** [comment]
Explanation: The layer in the selected instance was retrieving L2A images. The `sentinelhub` python package used the scenes available in the Sentinel-2 L1C dataset, which contained more images for the requested area.
