### ISSUE TITLE
Support querying for L2A products

### ISSUE THREAD

**Issue by blazs** [sentinel-hub/sentinelhub-py#21]
Currently the function [`OgcRequest.get_dates`](http://sentinelhub-py.readthedocs.io/en/latest/data_request.html#sentinelhub.data_request.OgcRequest.get_dates) queries dates for which L1C products are available. It does so regardless of whether source in [Sentinel Hub Configuration Utility](https://apps.sentinel-hub.com/configurator/#/) is set to `L1C` or  something else (such as `L2A`).

Although there is a plan to have an `L2A` for each `L1C` product, we currently provide few `L2A` products. Consequently, when one has source set to `L2A`  in the Configuration Utility, some queries may result in empty images (see issue #20 ).

We should fix this in the upcoming releases.

**Comment by batic** [comment]
This has already been identified and added to list of "improvements", see https://git.sinergise.com/eo/research/wikis/Application-Ideas under "Support all S-H datasources"

**Comment by mkadunc** [comment]
Has this been fixed with v.1.1 ?

**Comment by AleksMat** [comment]
Yes, since version 1.1.0 the package supports Senintel-2 L2A, Sentinel-1, Landast 8, MODIS and DEM data sources. Therefore I am closing this issue.
