### ISSUE TITLE
Wrong AWS Sentinel-2 query results 

### ISSUE THREAD

**Issue by vmyrgiotis** [sentinel-hub/sentinelhub-py#210]
**Describe the bug**

The get_area_info() function returns wrong results for queries on the AWS Sentinel-2 data pool. Most of the returned tiles do not correspond to the queried area. This problem has been confirmed for different areas in EPSG:32630 (UTM 30N). 

To reproduce run :

from sentinelhub import WebFeatureService, BBox, CRS, DataSource, SHConfig, AwsTileRequest,AwsTile,get_area_info
from sentinelhub import BBoxSplitter, OsmSplitter, TileSplitter, CustomGridSplitter, UtmZoneSplitter, UtmGridSplitter
import pandas as pd 

search_time_interval = ('2017-01-01T00:00:00','2021-12-31T23:59:59') # time interval for query

bbbox_england = BBox(((-3.3837890625, 52.697262335838026), (-2.65869140625, 53.305202055706545)), crs=CRS('4326')) ## bbox covering a small area in England (United Kingdom)

datainfo = pd.DataFrame(columns=['productIdentifier','tilecode','completionDate'])
for tile_info in get_area_info(bbbox_england, search_time_interval): datainfo = datainfo.append({'productIdentifier': tile_info['properties']['productIdentifier'],'tilecode' : tile_info['properties']['title'][49:55],'completionDate': tile_info['properties']['completionDate'][:10]}, ignore_index=True) ## create a dataframe to store the results of the query including the sentinel-2 tile code name

set(datainfo.tilecode) # to see tile codes of the query results

**Expected behavior**

When running set(data.tilecode) the unique tile code names in the query results should be T30XXX since the area is in England which has a UTM 30N (https://mangomap.com/robertyoung/maps/69585/what-utm-zone-am-i-in-?field=gid&value=61&layer=ad409ec0-cf2c-11e7-847d-06765ea3034e&field=gid&value=90&layer=ad409ec0-cf2c-11e7-847d-06765ea3034e) and UTM is shown in the 2nd and 3rd letter of the tile code name. If you run the above code you will probably be seeing some T01XXX which correspond to areas in the pacific ocean (https://mangomap.com/robertyoung/maps/69585/what-utm-zone-am-i-in-?field=gid&value=61&layer=ad409ec0-cf2c-11e7-847d-06765ea3034e)

**Environment**

python 3.6 , python 3.7

**Comment by batic** [comment]
Hi @vmyrgiotis ,

What you describe is true, but it is not the bug in sentinelhub-py that is the culprit. The issue is some wrong data (wrong geometries) of some tiles in the OpenSearch service that is being queried.

I suggest you try using [Catalog API](https://docs.sentinel-hub.com/api/latest/api/catalog/). The minimal working example for your case would be:

```python
from sentinelhub import SentinelHubCatalog, DataCollection, BBox, CRS
import geopandas as gpd

search_time_interval = ('2018-01-01T00:00:00','2018-12-31T23:59:59') # time interval for query
bbbox_england = BBox(((-3.3837890625, 52.697262335838026), (-2.65869140625, 53.305202055706545)), crs=CRS('4326')) ## bbox covering a small area in England (United Kingdom)

catalog = SentinelHubCatalog()
tiles_iterator = catalog.search(collection=DataCollection.SENTINEL2_L1C, time=search_time_interval, bbox=bbbox_england)
tiles = [tile for tile in tiles_iterator]

tiles_gdf = gpd.GeoDataFrame.from_features(tiles, crs='epsg:4326')
```

Running `tiles_df['proj:epsg'].unique()` on that will return only single UTM zone:
```
array([32630])
```

At some point in the (near?) future, we will fix the wrong items in the OpenSearch database, but as it is out of my hands, I unfortunately cannot give you a timeline.

**Comment by vmyrgiotis** [comment]
Thank you @batic !
