### ISSUE TITLE
More data on failed request?

### ISSUE THREAD

**Issue by PeterFogh** [sentinel-hub/sentinelhub-py#22]
Hello, I'm a new user of `sentinelhub-py`, and I'm currently trying out different calls and custom configuration layers.
However, at times I find that my requests fail, and using `sentinelhub-py` the only message I get is `Failed to download from <URL>`. Calling the HTTP GET request in the browser I found the ServiceException tag which is much more descriptive of the error. In my example it says:
```
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wcs/1.0.0/OGC-exception.xsd">
<ServiceException>
<![CDATA[ Failed to evaluate script! ]]>
</ServiceException>
</ServiceExceptionReport>
```

This way it can be seen that the error is due to the script for the respective configuration layer.

Could someone extend the raise of DownloadFailedException at line 210 in [sentinelhub/download.py](https://github.com/sentinel-hub/sentinelhub-py/blob/master/sentinelhub/download.py) with this more descriptive information?

**Comment by AleksMat** [comment]
Hi PeterFogh,

we have just released version `1.0.7` of the package where we improved handling of failed download errors. We also implemented your proposal and now in case of bad user request the `DownloadFailedException` also contains error message obtained from the server.

Thanks for a good suggestion.
