### ISSUE TITLE
Sentinel-2 L2A products query with get_area_info

### ISSUE THREAD

**Issue by pesekon2** [sentinel-hub/sentinelhub-py#221]
When doing a `get_area_info` request the way described below, I receive no L2 products. I have a feeling that it used to return both L1 and L2 products before, because I didn't make any change with my code and I used to receive L2 products, but maybe I just remember it wrongly. 

```
import datetime
from sentinelhub import CRS, get_area_info, BBox
bb = BBox('14.1575,49.8967,14.7763,50.2224', CRS.WGS84)
get_area_info(bb, (datetime.date(2018, 4, 7), datetime.date(2018, 5, 10)), 20)
```

Is the change of the behaviour described possible? In the case I am wrong and no change has caused this, is there any similar way to get the info also for L2 products covering the area?

Using `sentinelhub==3.4.0`.

**Comment by batic** [comment]
Hi @pesekon2 ,

OpenSearch implementation only works with Sentinel-2 L1C products. 

In order to get L2A information, you can use SentinelHub's `CatalogAPI` (to get tiles of any collection imported with SentinelHub):

```python
import datetime
from sentinelhub import CRS, BBox, SentinelHubCatalog, DataCollection

catalog = SentinelHubCatalog()

bb = BBox('14.1575,49.8967,14.7763,50.2224', CRS.WGS84)
time_interval = time=(datetime.date(2018, 4, 7), datetime.date(2018, 5, 10))

searcher = catalog.search(bbox=bb, time=time_interval, collection=DataCollection.SENTINEL2_L2A)
info = list(searcher)
```

**Comment by pesekon2** [comment]
Hi @batic,

Thanks, I'll try to follow this way then. 

But if I understand [1] correctly, I actually cannot do this without an account on sentinelhub, because I have to configure the `SentinelHubCatalog()` object, right? So every user of the tool would need a sentinelhub account extra to the AWS one. Or is there any way to do it without this account?

[1] <https://sentinelhub-py.readthedocs.io/en/latest/configure.html#sentinel-hub-configuration>

**Comment by gmilcinski** [comment]
You are right, Sentinel Hub account is needed for using Catalogue service. There is currently no alternative option to automatically query L2A data on this AWS repository.  
Note that there are trial accounts available for Sentinel Hub, which should allow you to make up to 100.000 queries over a period of a month.

**Comment by pesekon2** [comment]
Okay, thanks for the quick reply. I'll go for that.
