### ISSUE TITLE
[BUG] SAFE download format doesn't fetch QI_DATA files with Sentinel 2 L1C v04.00

### ISSUE THREAD

**Issue by anthony-scarth** [sentinel-hub/sentinelhub-py#231]
**Describe the bug**
Sentinel 2 L1C Product Version 04.00 has some significant changes to the contents of the QI_DATA folder and the sentinelhub downloader no longer fetches them correctly (when downloading in SAFE format - other downloads untested)

**_The main issue is that the contents of the QI folder which used to be GML and are now JP2_**
There have also been some name changes, reducing the total number of files available

A comparison of the contents can be seen with:
```
aws s3 ls s3://sentinel-s2-l1c/tiles/30/U/VD/2022/1/27/0/qi/ --request-payer requester  # new format
aws s3 ls s3://sentinel-s2-l1c/tiles/30/U/VD/2022/1/24/0/qi/ --request-payer requester  # old format
```

**To Reproduce**

Run the following python lines and inspect the downloaded data
```
from sentinelhub.data_request import download_safe_format
download_safe_format(
            product_id="S2B_MSIL1C_20220127T113309_N0400_R080_T30UVD_20220127T121733",
            folder="/tmp",
            redownload=True,
        )
```
The new JP2 files will be missing from the downloaded QI_DATA folder at:
/tmp/S2B_MSIL1C_20220127T113309_N0400_R080_T30UVD_20220127T121733.SAFE/GRANULE/L1C_T30UVD_A025560_20220127T113435/QI_DATA

**Expected behavior**

The downloader should fetch the new versions of these files
e.g.
DETFOO_B01.jp2 and QUALIT_B01.jp2
and structure them in the QI_DATA subfolder of the SAFE format

NOTE: they will need to be renamed upon download to MSK_DETFOO_B01.jp2 and MSK_QUALIT_B01.jp2 to match ESA's format!

e.g. Within 
S2B_MSIL1C_20220127T113309_N0400_R080_T30UVD_20220127T121733.SAFE/GRANULE/L1C_T30UVD_A025560_20220127T113435/QI_DATA

Should be:
./MSK_DETFOO_B01.jp2
./MSK_QUALIT_B01.jp2
./MSK_DETFOO_B02.jp2
etc...

**Environment**

sentinelhub 3.4.2

**Stack trace**

Output will likely print these warnings for all "missing" files (but otherwise complete the download as normal):
```
SHRuntimeWarning: File in location s3://sentinel-s2-l1c/tiles/37/P/CS/2022/1/26/0/qi/MSK_DEFECT_B01.gml is missing
```

**Additional Context**

I've done some investigation and the problem is likely to stem from this function hard-coding a ".gml" extension when looking for these files (and also referencing the prefix "MSK_" which doesn't exist for the JP2 files in the S3 structure):
https://github.com/sentinel-hub/sentinelhub-py/blob/master/sentinelhub/aws.py#L643

To test, I've tried setting the above to .jp2 and removing "MSK_" which makes the "not found" warnings disappear (so presumably correctly detects the files on S3). However it still does not download the files, so something else must need changing.

The line calling the above is here:
https://github.com/sentinel-hub/sentinelhub-py/blob/master/sentinelhub/aws_safe.py#L226
which I imagine needs to account now for new and old formats (and set the MimeType appropriately for get_qi_name() ?)

The list of QI filenames will also need changing for this product version:
https://github.com/sentinel-hub/sentinelhub-py/blob/master/sentinelhub/constants.py#L475
to QI_LIST = ['DETFOO', 'QUALIT']

**Comment by batic** [comment]
Thanks for the detailed description of the issue.

We (Sentinel-Hub) unpack the .SAFE files when copying them to AWS, and rename them to be consistent throughout the whole S-2 archive. The function implemented in the sentinelhub-py tries to reconstruct the unpacked/renamed files from AWS into the .SAFE format, but not all baselines are supported, and ESA has been changing how names are constructed, file types, etc. 

We know that `AwsService` class of the sentinelhub-py does not work for some (many?) baselines, but as sentinelhub-py is more an Python interface to SentinelHub service, this part is much lower on our priorities. That being said, we have plans to revisit this part of the code, unfortunately I cannot say when.

**Comment by JackLidge** [comment]
I've also been running into this error - are there any workarounds that can be used until it is fixed in the SentinelHub code?

Or any advice as to where this error can be fixed myself in the SentinelHub code?

**Comment by anthony-scarth** [comment]
@JackLidge We have made some changes required to support the download of v04.00 QI products. 
The compatibility with older formats should also be retained.
Pull request is here: https://github.com/sentinel-hub/sentinelhub-py/pull/240

For now, you will have to manually install the fork.

**Comment by JackLidge** [comment]
Great thanks @anthony-scarth! I'll be sure to check it out

**Comment by AleksMat** [comment]
The new `sentinelhub-py` version `3.5.0` now supports all baselines up to and including `04.00`.
