### ISSUE TITLE
How to download multiple images from any location

### ISSUE THREAD

**Issue by srinath-hekma** [sentinel-hub/sentinelhub-py#232]
Does this work with any set of long and lat? Please help me with downloading multiple images!

**Comment by AleksMat** [comment]
Hi @srinath-hekma,

please check [this documentation example](https://sentinelhub-py.readthedocs.io/en/latest/examples/data_search.html#Combine-Catalog-API-with-Process-API) that shows how to efficiently download multiple images.

**Comment by AleksMat** [comment]
Closing this. Feel free to reopen in case of further questions.
