### ISSUE TITLE
[HELP] TileSplitter function problems with Sentinel2 images 

### ISSUE THREAD

**Issue by SergioPovoli** [sentinel-hub/sentinelhub-py#241]
Dear all,
I’m Sergio and from my company I’m training to use sentinelhub services and api.

Specifically, I am using your API to locate and download Sentinel2 image projections of interest to me using the eolearn library.

I’ve encountered a problem in my workflow and wanted to try a question. The scenario is as follows:

I locate an area of interest
I create the grid of the patch of interest with the API “TileSplitter” correctly setting the CRS to EPSG:4326 (which in addition to being the crs of sentinel2 is also the crs of the polygon that describes my area of interest).
As you can see from the image the area in red is my area of interest, while in green are shown the output patch from the function TileSplitter.

```
finer_tile_splitter  = TileSplitter(
    [boundary_shape],
    CRS.WGS84,
    ('2017-11-1', '2020-11-2'),
    data_collection= DataCollection.SENTINEL2_L2A,
    config=config,
    tile_split_shape =6,
)
```
From this operation Note that some tiles are neither adjacent nor overlapping and therefore leaving areas not covered by any image and this for my type of application is a problem.

![image](https://user-images.githubusercontent.com/98584739/157011371-db7e47e5-1f9a-4330-9113-6167ccec550c.png)

Am I doing something wrong ? Or is it an API problem ? If it is an API problem can I fix it?

Thank you very much

**Comment by AleksMat** [comment]
Duplication of https://forum.sentinel-hub.com/t/tilesplitter-function-problems-with-sentinel2-images/5141
