### ISSUE TITLE
Basic question: Recording frequencies

### ISSUE THREAD

**Issue by saanasum** [sentinel-hub/sentinelhub-py#25]
I downloaded images using a defined time range ('2017-03-01','2017-10-31). I recognized that the recording frequency is only five days for my investigated area because I only got images every five days. Is that the normal recording rate/frequency? 

I used:

```
wcs_true_color_request = WcsRequest(data_folder='/home/Test/',
                                    layer='TRUE_COLOR',
                                    bbox=test_bbox,
                                    time=('2017-03-01','2017-10-31'),
                                    resx='10m', resy='10m',
                                    image_format=MimeType.TIFF,
                                    instance_id=INSTANCE_ID)
wcs_bands_img = wcs_true_color_request.save_data()
```

**Comment by batic** [comment]
The Sentinel-2 constellation only recently reported 5-day revisit over whole world (https://earth.esa.int/web/sentinel/news/-/article/sentinel-2-images-the-globe-every-5-days), but depending on your latitude, 5-day repetition sounds quite normal.

**Comment by batic** [comment]
As this is not an issue of the lib, I am closing the thread. You are also welcome to ask questions on our forum: https://forum.sentinel-hub.com/

**Comment by saanasum** [comment]
Thank you.
