### ISSUE TITLE
[HELP] SLSTR LST

### ISSUE THREAD

**Issue by AdrienWehrle** [sentinel-hub/sentinelhub-py#253]
Hi!

after some extensive research I couldn't find a way to access and download Sentinel-3 SLSTR Land Surface Temperature (LST) Level-2 data with `sentinelhub-py` (either by direct product download or through a custom script). Maybe it's simply because it isn't available?

Thank you a lot in advance for your help!

**Comment by gmilcinski** [comment]
Your assumption is correct. Level 2 is not available yet for Sentinel-3 SLSTR. There is only Level 1. See [documentation](https://docs.sentinel-hub.com/api/latest/data/sentinel-3-slstr-l1b/)

**Comment by AdrienWehrle** [comment]
Thanks a lot for your quick reply!

**Comment by AdrienWehrle** [comment]
Hi @gmilcinski , do you by any chance know of an approximate delivery time for Sentinel-3 SLSTR L2 through `sentinelhub-py`? Should it be expected rather soon or is it a longer-term goal? Thank you a lot! :+1:

**Comment by Rapsodia86** [comment]
Hello!
Any plans to add L2 LST anytime soon?
