### ISSUE TITLE
sentinelhub pillow dependency

### ISSUE THREAD

**Issue by giswqs** [sentinel-hub/sentinelhub-py#254]
Does sentinelhub require a specific version of pillow? I installed sentinelhub through conda, and it fails `pip check`. 

> sentinelhub 3.4.4 has requirement pillow<=8.4.0,>=8.3.2, but you have pillow 9.1.0.

Steps to reproduce:
```
conda install -c conda-forge sentinelhub
pip check
```

**Comment by AleksMat** [comment]
This was resolved in `sentinelhub` version `3.5.0` (https://github.com/sentinel-hub/sentinelhub-py/pull/249). The new version is available on PyPI and can be installedt with pip. 

Note that the new version hasn't been yet updated on conda as the conda recipe update is waiting for an approval: https://github.com/conda-forge/sentinelhub-feedstock/pull/25.

**Comment by giswqs** [comment]
@AleksMat Thanks for clarifying. I am also building a conda recipe, so I can only use sentinelhub on conda-forge. I will wait for v3.5.0. Thanks.
