### ISSUE TITLE
Error when making a 'OgcRequest' data request, not recognising service type?

### ISSUE THREAD

**Issue by jens2121** [sentinel-hub/sentinelhub-py#38]
Currently trying to make a OgcRequest, however not having any luck and getting an error:
`ogc_tc_request = data_request.OgcRequest(layer='TRUE-COLOR-S2-L1C',
                                    service_type='WCS',
                                    data_folder=user_dir,
                                    bbox=farm_bbox,
                                    time=(start_date, end_date),
                                    size_x='20m', size_y='20m',
                                    image_format=MimeType.TIFF_d32f,
                                    custom_url_params={CustomUrlParam.SHOWLOGO: False})`

The error I get is:
`File "E:\xx_DJANGO_DEVELOPMENT\SentinelHub_June2018\lib\get_data_sentinelhub.py", line 117, in main
    true_color(farm_bbox, start_date, end_date, resolution, user_dir)
  File "E:\xx_DJANGO_DEVELOPMENT\SentinelHub_June2018\lib\get_data_sentinelhub.py", line 48, in true_color
    custom_url_params={CustomUrlParam.SHOWLOGO: False})
  File "C:\Anaconda2\envs\sentinelhub\lib\site-packages\sentinelhub\data_request.py", line 296, in __init__
    super(OgcRequest, self).__init__(**kwargs)
  File "C:\Anaconda2\envs\sentinelhub\lib\site-packages\sentinelhub\data_request.py", line 41, in __init__
    self.create_request()
  File "C:\Anaconda2\envs\sentinelhub\lib\site-packages\sentinelhub\data_request.py", line 314, in create_request
    self.download_list = ogc_service.get_request(self)
  File "C:\Anaconda2\envs\sentinelhub\lib\site-packages\sentinelhub\ogc.py", line 154, in get_request
    size_x, size_y = self.get_image_dimensions(request)
  File "C:\Anaconda2\envs\sentinelhub\lib\site-packages\sentinelhub\ogc.py", line 319, in get_image_dimensions
    raise ValueError("At least one of parameters 'width' and 'height' must have an integer value")
ValueError: At least one of parameters 'width' and 'height' must have an integer value`

But when I look at the ogc.py file at the 'get_image_dimensions', it seems to be expecting integers related to 'WFS' (or other), and not 'WCS' as requested...

Am I missing something in my request?

**Comment by azupanc** [comment]
For WCS requests use `WcsRequest` class: https://github.com/sentinel-hub/sentinelhub-py/blob/f8ff0a757dd497ce183a8b4162b1f25d3392bb45/sentinelhub/data_request.py#L402

**Comment by devisperessutti** [comment]
Usage example for `WcsRequest` can be found [here](http://sentinelhub-py.readthedocs.io/en/latest/examples/ogc_request.html#Web-Map-Service-(WMS)-and-Web-Coverage-Service-(WCS)).
