### ISSUE TITLE
[HELP] How to pass --no-sign-request in config.json

### ISSUE THREAD

**Issue by yurigba** [sentinel-hub/sentinelhub-py#394]
I want to be able to access a s3 bucket with the flag `--no-sign-request`, for example [this one](https://registry.opendata.aws/sentinel-2-l2a-cogs/).

Is it possible to pass this in the config.json?

**Comment by zigaLuksic** [comment]
Hi @yurigba, how (with what function/module) are you trying to access the bucket?

**Comment by yurigba** [comment]
I am trying to use the [ImportFromTiffTask](https://eo-learn.readthedocs.io/en/latest/reference/eolearn.io.raster_io.html#eolearn.io.raster_io.ImportFromTiffTask).

**Comment by zigaLuksic** [comment]
The `ImportFromTiffTask` has a parameter `filesystem`. You can provide an instance of `fs_s3fs.S3FS` filesystem (either constructed directly or by using the `eolearn.core.utils.fs.load_s3_filesystem` [utility function](https://eo-learn.readthedocs.io/en/latest/reference/eolearn.core.utils.fs.html#eolearn.core.utils.fs.load_s3_filesystem)).

This is also what is done behind the scenes. However we have encountered some limitations of `fs_s3fs` in the past, perhaps check the `S3FS` [docs](https://fs-s3fs.readthedocs.io/en/latest/) if what you need is enabled.

**Comment by yurigba** [comment]
I have tried to reproduce the error, but I couldn't. Probably it was a coincidence with a problem in my network. I will close the issue, since I couldn't reproduce and it is now working normally. If I get problems again I'll reopen.

Thanks for the help.
