### ISSUE TITLE
Swap opencv-python for opencv-python-headless

### ISSUE THREAD

**Issue by fanquake** [sentinel-hub/sentinelhub-py#40]
With the release of `opencv-python` [3.3.0.10](https://github.com/skvark/opencv-python/releases/tag/10), new dependencies were added to support Qt. This has made it harder to use `opencv-python` in some server environments were certain libraries might not be available, and/or not possible to install. See https://github.com/skvark/opencv-python/issues/44 for one such example.

In response opencv-python now provides [headless packages](https://pypi.org/project/opencv-python-headless/).

We are using `sentinelhub-py` in a server environment where installing the GUI related dependancies might not be possible, so for now we've just had to pin our opencv-python package to version `3.3.0.9`.

Would it be possible switch sentinelhub-py's requirement on `opencv-python` to `opencv-python-headless`? I've had a look through the code here, and done some testing locally that would seem to suggest the two could be swapped directly.

Interested in any thoughts on this. Thanks.

**Comment by AleksMat** [comment]
Hi fanquake,

thanks for raising this issue and pull request. At the moment we are also thinking about replacing `opencv-py` altogether (probably with `pillow`). There are also a few other issues that we have with OpenCV. For example the new version of OpenCV does not support reading of 15-bit JPEG2000 images (described in #33).

We have to run some tests and we will let you know as soon as possible.

**Comment by AleksMat** [comment]
Version `2.3.0` of  `sentinelhub` has now been released. We swaped `opencv-python` dependency with `Pillow`.

I hope that fixes the problem. Let us know if you will be able to run it in server environment.

**Comment by fanquake** [comment]
@AleksMat We've started using `2.3.0` in production, and everything is working as expected.
Thanks for the quick turnaround 👍
