### ISSUE TITLE
[BUG] Cannot import name 'MosaickingOrder' from 'sentinelhub'

### ISSUE THREAD

**Issue by taucler** [sentinel-hub/sentinelhub-py#402]
**Describe the bug**

Cannot import name 'MosaickingOrder' from 'sentinelhub' while running the notebook `process_request.ipynb` from the examples.

**To Reproduce**

1. Run the notebook through JupyterLab Desktop 3.6.1

**Expected behavior**

Expected to import the entire package properly.

**Environment**

`python3 3.10.6
sentinelhub 3.4.4
`
**Stack trace or screenshots**

![image](https://user-images.githubusercontent.com/56865664/218681442-975878f8-32bc-40b6-b685-f5bd4451e23f.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu 22.04.1 LTS
 - Browser chrome
 - Version 110.0.5481.77

**Additional context**

@mlubej

**Comment by mlubej** [comment]
@zigaLuksic is it possible that the examples are just outdated?

**Comment by zigaLuksic** [comment]
Hi @taucler,
the examples are made to be run with the latest version. You have a very old version installed.
