### ISSUE TITLE
Bug in aws.py File

### ISSUE THREAD

**Issue by Enforcer007** [sentinel-hub/sentinelhub-py#44]
Though the product is from L1C archive and generated from S2B instrument of Sentinel-2 Satellite.

I have faced an issue when trying to parse Product-Identifier of the Tile i.e, (S2B_OPER_MSI_L1C_TL_SGS__20180812T090522_A007481_T43QHV_N02.06) through a parser method i.e, AwsTile.tile_id_to_tile() and below is the error.

AwsTile.tile_id_to_tile(tile_id)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-67-af6f4d6eed3a> in <module>()
----> 1 AwsTile.tile_id_to_tile(tile_id)

~/.conda/envs/web-static/lib/python3.6/site-packages/sentinelhub/aws.py in tile_id_to_tile(tile_id)
    680         """
    681         if tile_id.split('_')[0] not in ['S2A', 'L1C','S2B']:
--> 682             raise ValueError('Transformation from tile_id to tile works currently only for Sentinel-2 L1C products')
    683 
    684         tile_info = get_tile_info_id(tile_id)

ValueError: Transformation from tile_id to tile works currently only for Sentinel-2 L1C products

I have added 'S2B' in line 681 as on of the element in the list and works properly..

**Comment by AleksMat** [comment]
Hi Enforcer007,

you are right, 'S2B' is also a valid prefix. We will fix the issue as soon as possible. Thanks for letting us know about this.

**Comment by AleksMat** [comment]
In the new package version `2.4.2` this has been fixed. Therefore I am closing the issue. Thanks again.
