### ISSUE TITLE
[FEAT]  SLSTR LST

### ISSUE THREAD

**Issue by Rapsodia86** [sentinel-hub/sentinelhub-py#446]
**What is the problem? Please describe.**

SLSTR LST level 2 product is still missing. Any plans to add it any time soon? #253 

**Here's the solution**

**Alternatives**

**Additional context**

**Comment by zigaLuksic** [comment]
Hi, judging by the [documentation](https://docs.sentinel-hub.com/api/latest/data/) of Sentinel Hub the L2 product is not available.

**Comment by zigaLuksic** [comment]
> Do you know whether it will be any time soon? Or it is not planned?

I asked the Sentinel Hub team and they said there are currently no plans for that.
