### ISSUE TITLE
Error in AwsTileRequest

### ISSUE THREAD

**Issue by Enforcer007** [sentinel-hub/sentinelhub-py#45]
Hi I'm getting error when I'm trying to create AwsTileRequest object. Even when I'm trying to run the sample code mentioned in the documentation I'm facing the below error.

`
from sentinelhub import AwsTile

tile_id = 'S2A_OPER_MSI_L1C_TL_MTI__20151219T100121_A002563_T38TML_N02.01'
tile_name, time, aws_index = AwsTile.tile_id_to_tile(tile_id)

from sentinelhub import AwsTileRequest

bands = ['B8A', 'B10']
metafiles = ['tileInfo', 'preview', 'qi/MSK_CLOUDS_B00']
data_folder = './AwsData'

request = AwsTileRequest(tile=tile_name, time=time, aws_index=aws_index,
                         bands=bands, metafiles=metafiles, data_folder=data_folder,
                         data_source=DataSource.SENTINEL2_L1C)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-104-7aacbaf30968> in <module>()
      7 request = AwsTileRequest(tile=tile_name, time=time, aws_index=aws_index,
      8                          bands=bands, metafiles=metafiles, data_folder=data_folder,
----> 9                          data_source=DataSource.SENTINEL2_L1C)

~/.conda/envs/web-static/lib/python3.6/site-packages/sentinelhub/data_request.py in __init__(self, tile, time, aws_index, data_source, **kwargs)
    676         self.data_source = data_source
    677 
--> 678         super(AwsTileRequest, self).__init__(**kwargs)
    679 
    680     def create_request(self):

~/.conda/envs/web-static/lib/python3.6/site-packages/sentinelhub/data_request.py in __init__(self, bands, metafiles, safe_format, **kwargs)
    587 
    588         self.aws_service = None
--> 589         super(AwsRequest, self).__init__(**kwargs)
    590 
    591     @abstractmethod

~/.conda/envs/web-static/lib/python3.6/site-packages/sentinelhub/data_request.py in __init__(self, data_folder)
     39         self.download_list = []
     40         self.folder_list = []
---> 41         self.create_request()
     42 
     43     @abstractmethod

~/.conda/envs/web-static/lib/python3.6/site-packages/sentinelhub/data_request.py in create_request(self)
    684         else:
    685             self.aws_service = AwsTile(self.tile, self.time, self.aws_index, bands=self.bands,
--> 686                                        metafiles=self.metafiles, data_source=self.data_source)
    687 
    688         self.download_list, self.folder_list = self.aws_service.get_requests()

~/.conda/envs/web-static/lib/python3.6/site-packages/sentinelhub/aws.py in __init__(self, tile_name, time, aws_index, data_source, **kwargs)
    467         self.data_source = data_source
    468 
--> 469         super(AwsTile, self).__init__(**kwargs)
    470         self.tile_url = None
    471 

TypeError: super(type, obj): obj must be an instance or subtype of type
`

**Comment by Enforcer007** [comment]
Now I haven't got an issue when I downloaded the package from git repo. But observing the issue if donwload from pip install sentinelhub.

**Comment by AleksMat** [comment]
The problem does not appear to me neither does it appear in [unit tests](https://travis-ci.org/sentinel-hub/sentinelhub-py/builds/414563052).

However I think I know the reason for this. The error happens if you work in Jupyter Notebook, import a class from a package, then change something in definition of the class  (in your case `AwsTile.tile_id_to_tile`), reinstall the package (if needed) and continue working with that class in the same notebook. Jupyter then somehow fails to update the definition of the class.

The solution for this is to restart the Jupyter's kernel and rerun the notebook.
