### ISSUE TITLE
ESA OSEO page invalid

### ISSUE THREAD

**Issue by psteinb** [sentinel-hub/sentinelhub-py#474]
Hi -

thanks for providing this python package. While going through the docs, I was interested in registering as a researcher to sentinal hub. The documentation says:

> If you are a researcher you can even apply for a free non-commercial account at [ESA OSEO page](https://earth.esa.int/aos/OSEO).

See the code for this:
https://github.com/sentinel-hub/sentinelhub-py/blob/98d0327e3929999ec07645f77b16fceb7f9c88b9/docs/source/configure.rst?plain=1#L85

But this links leads nowhere:
![image](https://github.com/sentinel-hub/sentinelhub-py/assets/1465603/eb7e7c78-4d8c-4f8a-989f-d984dd440bc8)

This would be great to fix.

**Comment by batic** [comment]
Thanks for bringing this to our attention. 

Will fix this shortly, in the mean time, please have a look at https://www.sentinel-hub.com/faq/it-possible-get-free-account-research-purposes/ 

Regards,
Matej

**Comment by batic** [comment]
Closing. Will be visible on readthedocs main with new release.
