### ISSUE TITLE
[HELP] Downloading full resolution for entire US State

### ISSUE THREAD

**Issue by melgor** [sentinel-hub/sentinelhub-py#503]
**Question**
I struggle with migrating to  SentinelHub API for downloading satellite images. My use case:
- download satellite images from ex. an entire state like Louisiana
- get these images in full resolution, 10m/px
- my current pipeline works on products (like `S2A_MSIL1C_20151022T170012_N0204_R026_T15SVR_20151022T170014.SAFE`) and would like to keep it in that format if possible. Raw images are also fine

**Additional context**
### 1st attempt 
I just used the migration guide. It was working perfectly. But as I encountered many images like those below, I decided to download specific products and check the nb of NaNs. If too much NaNs, download them next. But the 100-session limit makes it not usable for me ( as I check one by one each tile from US state, don't want to download all product from state and then check them)
<img width="415" alt="Screenshot 2023-12-01 at 10 03 30" src="https://github.com/sentinel-hub/sentinelhub-py/assets/2587438/96df8358-4b13-42de-ab89-6a9707c17d77">

### 2nd attempt
I decided to check the newer API, without calling it by request. There are so many new APIs there, tried to figure our pipeline for myself. I mainly followed [Catalog API + Process API](https://sentinelhub-py.readthedocs.io/en/latest/examples/data_search.html#Combine-Catalog-API-with-Process-API) Here it is:
1. Use `TileSplitter` to get `BBoxes` per tile. 
2. Use `SentinelHubCatalog` to find products for given `BBoxes` and time-interval
3. Use `SentinelHubRequest` + `SentinelHubDownloadClient` 

Issues:
1. I'm not able to specify a resolution of 10m/px per `BBox` as it will result in 10980x10980 where max is 2500
2. Even if I would download it, I'm not sure how it relates to product names. I would like to have them also

### Summary
The question is: how to download full-resolution satellite images, best with their product names? Is S3-bucker the way to go?

**Comment by willrayeo** [comment]
Hi, I'm not sure which migration guide you're referring to? Perhaps this [one](https://dataspace.copernicus.eu/news/2023-9-28-accessing-sentinel-mission-data-new-copernicus-data-space-ecosystem-apis)? If so, I recommend asking your question in the community forum which you can find [here](https://helpcenter.dataspace.copernicus.eu/hc/en-gb/community/topics)

**Comment by melgor** [comment]
Yes, exactly this one migration guide. But I have no issue with migration, just a limit of 100 sessions stops me from running batch queries. I just wanted to present whole story.

The main question in this issue is:
How to download full-resolution satellite images (10kx10k, 10m/px resolution), using `sentinelhub-py`?

**Comment by gmilcinski** [comment]
Have you tried large area utilities example?
https://sentinelhub-py.readthedocs.io/en/latest/examples/large_area_utilities.html/v1/catalog/1.0.0/search

**Comment by gmilcinski** [comment]
Depends what you want to do. If you just want a full scene, then downloading it from S3 is probably easiest. 
If you need something more advanced, then you will have to stich the images together.

**Comment by melgor** [comment]
Thanks for help. I'm really pleased with help from you guys and descent code documents.
