### ISSUE TITLE
[HELP] Sentinel-3 OLCI L1B documentation

### ISSUE THREAD

**Issue by AdrienWehrle** [sentinel-hub/sentinelhub-py#530]
Hi! 

I was browsing through the description of the Sentinel Hub data collections available in `sentinelhub-py` and realized I struggle understanding the Sentinel Hub variable associated with the Sentinel-3 L1B product.

The documentation of the [Sentinel-3 OLCI L1B Sentinel Hub data collection](https://docs.sentinel-hub.com/api/latest/data/sentinel-3-olci-l1b/) specifies "[Level-1B](https://sentinel.esa.int/web/sentinel/user-guides/sentinel-3-olci/product-types/level-1b) provides calibrated, ortho-geolocated and spatially re-sampled Top Of Atmosphere (TOA) radiances for the 21 OLCI spectral bands." and then in the `Units` section "Radiance (`mW.m-2.sr-1.nm-1`). Note that Sentinel Hub returns reflectance." and further down in the `Sentinel Hub units` section of the band description: "Sentinel Hub Units: REFLECTANCE".

Am I understanding correctly that the variable returned is a radiance in `mW.m-2.sr-1.nm-1` whose field name in the Sentinel Hub data collection is reflectance? Or is Sentinel Hub applying a radiance-to-reflectance algorithm to L1B to return an actual reflectance?

Thank you a lot in advance for your help!

**Comment by maximlamare** [comment]
Hi Adrian,

In Sentinel Hub, S3 OLCI is converted to reflectance using the standard formula. We are planning to add direct access to radiances in the future too. This will be announced through our usual channels when available.

**Comment by AdrienWehrle** [comment]
Hi Maxim,

thanks a lot for your answer! So what is presented as L1B by Sentinel Hub (eg [here](https://docs.sentinel-hub.com/api/latest/data/sentinel-3-olci-l1b/)) is actually L2? 

Since the processing level given by ```sentinelhub.DataCollection.SENTINEL3_OLCI``` is L1B and Copernicus states the following (eg [here](https://sentiwiki.copernicus.eu/web/olci-products)):

" 
[Level-1 processing](https://sentiwiki.copernicus.eu/web/olci-processing#L1-Algorithms) uses Level-0 products to compute radiometrically calibrated, georeferenced and annotated **radiances** for each OLCI channel. Several contextual elements are also computed such as quality flags and pixel classification flags. Two specific calibration mode are also part of this Level-1 processing : the OLCI radiometric Calibration and the OLCI Spectral Calibration

[Level-2 processing](https://sentiwiki.copernicus.eu/web/olci-processing#L2-Algorithms) uses Level-1 products inside the two main processes: the Ocean processing and the Land processing. A first pre-processing module is converting the TOA radiances into **reflectance** corrected for gaseous absorption. Then, each process is providing a specific product
"

or also [here](https://sentiwiki.copernicus.eu/web/olci-processing) where the radiance to reflectance conversion is presented as an L2 algorithm.

If so, I think it would reduce confusion to call the collection and associated documentation L2 and not L1B!

Thank you a lot for your help!

**Comment by maximlamare** [comment]
I wouldn't call it Level-2: it's simply a conversion of units, so it is still the same level product, as there is no correction applied. 
The formula is the one found in user documentation for Sentinel-3:

<img width="140" alt="Screenshot 2024-05-27 at 12 31 07" src="https://github.com/sentinel-hub/sentinelhub-py/assets/32132761/55d67118-411c-4634-bfd4-a09f7e3de182">

<img width="398" alt="Screenshot 2024-05-27 at 12 32 30" src="https://github.com/sentinel-hub/sentinelhub-py/assets/32132761/e3cd5dc9-aa27-4211-83b4-6dac802663c5">

**Comment by AdrienWehrle** [comment]
Great, thanks a lot! So I understand from this that it's close to a L2 product since it's a reflectance and not a radiance (computed following the equation you just shared), yet not an actual L2 because there's no eg atmospheric correction (as eg presented [here](https://sentiwiki.copernicus.eu/web/olci-processing#OLCIProcessing-GasCorrection) for OLCI L2 processing).

I think this data collection is then similar to the reflectances we used to get from passing the OLCI L1 EFR into the SNAP Rad2Refl processor, so that's great!

Thank you for your help on this, Maxim! And I hope you're doing well :)
