### ISSUE TITLE
Possibility to provide own bbox list

### ISSUE THREAD

**Issue by wouellette** [sentinel-hub/sentinelhub-py#54]
I would like the method implemented in `sentinelhub-py/sentinelhub/areas.py `to allow me to create a `<sentinelhub.areas.BBoxSplitter object>` based on a bbox list which is already existing.

The need stems from the fact that I have a reference tile grid (contiguous bboxes covering the entire globe) with uuid's, and I want to make sure the processing is performed consistently within these grid tiles, and not have the AOI split up into new tiles which do not correspond to this 'reference' grid. 

Essentially, I just want to provide my list of rectangular geometries (e.g. `shapely.geometry.box `objects) covering my AOI to the AreaSplitter method, and have this list returned as an `<sentinelhub.areas.BBoxSplitter object>, ` so that I can still leverage the other attributes from the method like `get_info_list()` or `get_bbox_list()`.

Thanks in advance!

**Comment by AleksMat** [comment]
Hi William,

In the new version `2.5.0` we plan to add an option of initializing `sentinelhub.BBox` with any `shapely.geometry` object. BBox coordinates will be taken from `shapely` object's `bounds` property. For your case this should simplify procedure of getting a list of `sentinelhub.BBox` objects. 

I agree that it might be useful to also have some sort of `CustomGridSplitter` but we have to decide what more this object could do. The following would definitely be useful:
- Filtering given bounding boxes according to their intersections with `shape_list` geometries.
- Option to subdivide given bounding boxes into smaller parts.

Is there something else you might find useful about this object? What should info list return?

We plan to release a new version in next few weeks and we can add this as well.

**Comment by wouellette** [comment]
Hi Matej,

For the time being, I see that the info list returns the parent BBox  , the
index_x and index_y and the crs. If a  CustomGrid  is provided, this one
may have other attributes of interest which could be carried over? They may
have name, id, etc. The problem is that carrying over unknown attributes
may be risky business, so probably not suitable. I think if the CustomGrid has
an id, it should be carried over. This will guarantee that it can be linked
back to the reference grid after the processing.

Keep up the good work!

Regards,

William


Le ven. 7 déc. 2018 à 11:50, Matej Aleksandrov <notifications@github.com> a
écrit :

**Comment by AleksMat** [comment]
Ok, for now I would carry over the index of bbox in the custom grid. If having an option of subdividing the given bboxes from the custom grid, there could be also indices of such subdivision.

**Comment by AleksMat** [comment]
The new package version `2.5.0` is finally released and with it an implementation of `CustomGridSplitter`. An [example](https://sentinelhub-py.readthedocs.io/en/latest/examples/large_area_utilities.html#Splitting-in-custom-grid) and [class documentation](https://sentinelhub-py.readthedocs.io/en/latest/areas.html#sentinelhub.areas.CustomGridSplitter) are also available. I hope you will find it useful and let us know if you have any more suggestions for improvements. :)
