### ISSUE TITLE
[BUG] Inconsistency in the Statistical API response

### ISSUE THREAD

**Issue by parbelet** [sentinel-hub/sentinelhub-py#547]
**Describe the bug**

The statistical API aggregation response is wrong.

**To Reproduce**

I will use the [10m Annual Land Use Land Cover (9-class)](https://collections.sentinel-hub.com/impact-observatory-lulc-map/) collection for the sake of clarity

Given a geometry, in WGS84 coordinates, which corresponds to a vineyard parcel:

```python
geom = {"type": "MultiPolygon", "coordinates": [[[[-69.25938266016884, -33.606832780293296], [-69.26059349758972, -33.60682715386169], [-69.26163859816909, -33.60635828209652], [-69.26185275119607, -33.6063617921014], [-69.26182899745895, -33.6071406379151], [-69.25709711300503, -33.607522723568685], [-69.25709711300426, -33.6069279250077], [-69.25938266016884, -33.606832780293296]]]]}
```

1. Visualize on the [EO Browser](https://apps.sentinel-hub.com/eo-browser/?zoom=17&lat=-33.60694&lng=-69.25947&themeId=DEFAULT-THEME&visualizationUrl=U2FsdGVkX19kfQ67Dq%2F95cb3eEzyRpQbURYUzFm4lf7rcyyEHRZUVrI4MhY2AAfPIIs6rbsCT0SCwm8QTJvramtBv%2F2kFUc3LGtZxvBIfkFIxLhZn23NT9i0tH61iAQe&datasetId=IO_LULC_10M_ANNUAL&fromTime=2022-01-01T00%3A00%3A00.000Z&toTime=2022-01-01T23%3A59%3A59.999Z&layerId=IO-LAND-USE-LAND-COVER-MAP&demSource3D=%22MAPZEN%22) the LULC distribution of the pixels on the parcel for 2022 ✅ 

![image](https://github.com/user-attachments/assets/bcf39df5-f67b-4d03-a34b-d601ce61397f)

-> we see that most of the parcel is classified as `Crops`, which is consistent

2. Verify the consistency using the Processing API ✅ 

```python
from sentinelhub import SHConfig
import datetime
import os

import numpy as np

from typing import Union, Tuple

from shapely.ops import transform
from shapely.geometry import Polygon, MultiPolygon, GeometryCollection

from pyproj import Transformer
from shapely.geometry import mapping, Point, shape

from sentinelhub.geo_utils import get_utm_crs

from sentinelhub import (
    CRS,
    BBox,
    Geometry,
    DataCollection,
    DownloadRequest,
    MimeType,
    MosaickingOrder,
    SentinelHubDownloadClient,
    SentinelHubRequest,
    bbox_to_dimensions,
)


def to_utm_crs(geom: Union[Polygon, MultiPolygon]) -> Tuple[Union[Polygon, MultiPolygon], pyproj.CRS]:
    """Project a geometry in WGS84 coordinates to UTM
    """
    wgs84 = pyproj.CRS('EPSG:4326')
    if isinstance(geom, (MultiPolygon, GeometryCollection)):
        if len(geom.geoms) == 0:
            return None, None
        p = geom.geoms[0].exterior.coords[0]
    else:
        p = geom.exterior.coords[0]
    p = Point(*p)
    utm_crs = get_utm_crs(p.x, p.y, source_crs=CRS.WGS84)
    utm_crs = pyproj.CRS(f'EPSG:{utm_crs.epsg}')
    project = pyproj.Transformer.from_crs(wgs84, utm_crs, always_xy=True).transform
    utm_geom = transform(project, geom)
    return utm_geom, utm_crs


eval_script = """//VERSION=3

function setup() {
    return {
        input: [
            "lulc",
            "dataMask"
        ],
        output: [
            {   
                id: "lulc",
                bands: 1,
                sampleType: "UINT8"
            },
            {
                id: "dataMask",
                bands: 1,
            }            
        ]
    }
}
  
function evaluatePixel(sample) {
    return {
        lulc: [sample.lulc],
        dataMask: [sample.dataMask]
    }
}
"""

annual_lulc_collection = DataCollection.define_byoc(
    collection_id="0ed26381-7344-4281-b180-66f3da521f75"
)
sh_input_data = SentinelHubRequest.input_data(
    data_collection=annual_lulc_collection,
    time_interval=("2022-01-01", "2022-04-01"),
)
sh_config = SHConfig()


utm_envelop, utm_crs = to_utm_crs(shape(geom))

request = SentinelHubRequest(
    evalscript=eval_script,
    input_data=[sh_input_data],
    responses=[SentinelHubRequest.output_response("lulc", MimeType.TIFF)],
    geometry=Geometry(utm_envelop, crs=CRS(utm_crs)),
    resolution=(10, 10),
    config=sh_config,
)


imgs = request.get_data()
image = imgs[0]

```
this gives a consistent image with 75% of Crops within the parcel

![image](https://github.com/user-attachments/assets/2028ff45-04cf-4456-9b6e-63ac309e5756)

3. Get the result with the Statistical API 🔴 

```python
from sentinelhub import SHConfig
import datetime
import os

import numpy as np

from sentinelhub.time_utils import parse_time
from sentinelhub import Geometry, SHConfig, CRS
from sentinelhub.data_collections import DataCollection
from sentinelhub.api.statistical import InputDataDict
from sentinelhub.api.statistical import SentinelHubStatistical
from sentinelhub.api.statistical import SentinelHubStatisticalDownloadClient


eval_script = """//VERSION=3

function setup() {
    return {
        input: [
            "lulc",
            "dataMask"
        ],
        output: [
            {   
                id: "lulc",
                bands: 1,
                sampleType: "UINT8"
            },
            {
                id: "dataMask",
                bands: 1,
            }            
        ]
    }
}
  
function evaluatePixel(sample) {
    return {
        lulc: [sample.lulc],
        dataMask: [sample.dataMask]
    }
}
"""

annual_lulc_collection = DataCollection.define_byoc(
    collection_id="0ed26381-7344-4281-b180-66f3da521f75"
)
sh_input_data = SentinelHubStatistical.input_data(
    data_collection=annual_lulc_collection,
)
sh_config = SHConfig()

histogram_calculations = {
    "lulc": {
        "histograms": {
            "default": {
                "bins": [1, 2, 4, 5, 7, 8, 9, 10, 11, 12]
            }
        }
    }
}

time_interval = ("2022-01-01", "2023-01-01")

aggregation = SentinelHubStatistical.aggregation(
    evalscript=eval_script,
    time_interval=time_interval,
    aggregation_interval="P1Y",
    resolution=(10, 10)  # in UTM CRS: meters
)
config = SHConfig()
client = SentinelHubStatisticalDownloadClient(config=config)

utm_geom, utm_crs = to_utm_crs(geom)

requests = list()
request = SentinelHubStatistical(
    aggregation=aggregation,
    calculations=histogram_calculations,
    input_data=[sh_input_data],
    geometry=Geometry(utm_geom, crs=CRS(utm_crs)),
    config=config,
)
requests.append(request)

# Pass request objects together to a download client object,
# which will execute them in parallel using multiple threads.
download_requests = [
    request.download_list[0] for request in requests
]
stats =  client.download(download_requests)

histogram = stats[0]['data'][0]['outputs']['lulc']['bands']['B0']['histogram']
histogram
```

gives 
```
{'bins': [{'lowEdge': 1, 'highEdge': 2, 'count': 0},
  {'lowEdge': 2, 'highEdge': 4, 'count': 0},
  {'lowEdge': 4, 'highEdge': 5, 'count': 0},
  {'lowEdge': 5, 'highEdge': 7, 'count': 0},
  {'lowEdge': 7, 'highEdge': 8, 'count': 0},
  {'lowEdge': 8, 'highEdge': 9, 'count': 0},
  {'lowEdge': 9, 'highEdge': 10, 'count': 0},
  {'lowEdge': 10, 'highEdge': 11, 'count': 0},
  {'lowEdge': 11, 'highEdge': 12, 'count': 313}],
 'overflowCount': 0,
 'underflowCount': 0}
```

that is 100% Rangeland 🔴 

**Expected behavior**

The results of the Statistical API must be consistent with what we observe with the Processing API or the EOBrowser

**Environment**

Details of the python environment
```
sentinelhub = "==3.10.1"
```

Python 3.9

**Desktop (please complete the following information):**

 - OS: macOS 14.5

**Additional context**

**Comment by mlubej** [comment]
Hi @parbelet!

This one is a tricky trap, but it's not a bug. I think the issue is that you are doing a yearly aggregation over the yearly span, and I think it's taking into account the 2022 land cover map as well as the 2023 land cover map, since the maps are actually pinned to the January first each year.

Or perhaps there really is a bug in how the `P1Y` is treating the calculations, not sure about this one.

However, if you do e.g. a time interval from `2022-01-01` to `2023-01-02` (so both maps are taken into account) and do the request with a shorter window, say `P1M` or even `P1D`, you get two results

<img width="621" alt="image" src="https://github.com/user-attachments/assets/34f3207d-3997-4358-aa2e-80d5610c3386">

The first one is what you expect, and the second one is what you get above, which I assume is the land cover map for 2023

So, what bothers me here is that I have to extend the end date to make the interval inclusive, while for `P1Y` it seems to exclude the 2022-01-01 date and include the 2023-01-01 date.

My suggestion would be to keep the temporal aggregation windows short in such cases where you have only one ingested image per year

<img width="200" alt="image" src="https://github.com/user-attachments/assets/12063a9b-e01c-4740-97b1-eddb3ce96ce7">

**Comment by parbelet** [comment]
Thank you very much @mlubej for your quick answer!

it wasn't obvious that the annual data would only be available on 1 January indeed: I managed to have more consistent results specifying an `aggregation_interval="P1D"` instead of `aggregation_interval="P1Y"`  (which is a bit counterintuitive to get annual results I must say 😄 )
