### ISSUE TITLE
Sentinel-1 Image Download

### ISSUE THREAD

**Issue by lamductan** [sentinel-hub/sentinelhub-py#59]
Could you please give me an example of downloading Sentinel-1 images? I follow the example of Sentinel-2 but `get_tiles()` method doesnot work with Sentinel-1.

**Comment by devisperessutti** [comment]
Hi @lamductan 

The example 15 in this [notebook](https://github.com/sentinel-hub/sentinelhub-py/blob/master/examples/ogc_request.ipynb) should help you out.
