### ISSUE TITLE
Incorrect format string in log message causes TypeError

### ISSUE THREAD

**Issue by dhepper** [sentinel-hub/sentinelhub-py#60]
A log message in `opensearch.get_tile_info_id` uses `%d` to format a tile ID, which raises a TypeError because tile IDs are strings.

Workaround:

    logging.getLogger('sentinelhub.opensearch').setLevel(logging.CRITICAL)

**Comment by AleksMat** [comment]
Hi @dhepper,

Your pull request has been merged to develop. It will be merged to master when we release a  new package version (should be some time in next few weeks).

Thanks a lot for reporting and fixing this issue. :+1:

**Comment by dhepper** [comment]
Hi @AleksMat, great, thanks for the quick feedback!
