### ISSUE TITLE
MFA with sentinelhub.aws

### ISSUE THREAD

**Issue by evan-blaisdell** [sentinel-hub/sentinelhub-py#63]
Using sentinelhub.aws, I cannot download Sentinel imagery from S3 when using an AWS account that has a MFA (multi-factor authentication) requirement. I have verified that I can do so on an account that does not require MFA.

**Comment by vincentsarago** [comment]
Hi evan, from what I can see, the `sentinelhub.config` doesn't have option for `aws_session_token`

https://github.com/sentinel-hub/sentinelhub-py/blob/08a83b7f1e289187159a643336995d8369860fea/sentinelhub/config.py#L45-L48

It might be pretty strait forward to add it and then modify https://github.com/sentinel-hub/sentinelhub-py/blob/master/sentinelhub/download.py#L287-L309 to add `SHConfig().add_session_token`

**Comment by evan-blaisdell** [comment]
Well, that was easier than I thought it would be. Thanks. This is the first time I've delved into the guts.
