### ISSUE TITLE
Could not load necessary digital elevation model for orthorectification!

### ISSUE THREAD

**Issue by patrickcgray** [sentinel-hub/sentinelhub-py#67]
I was trying to load up some Sentinel-1 Data with orthorectification, basically following the tutorial jupyter notebook but changing the config to include orthorectification and I got the error:

`Server response: "java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not load necessary digital elevation model for orthorectification! Please try again later or without orthorectification."`

I've tried this three days in a row now and got the same response. Is there a way to tell what areas actually have orthorectification? I'm looking at the east coast of the United States. Is there any timeline for knowing when these areas will have orthorectified data if they currently don't or ways to fix this issue?

**Comment by gmilcinski** [comment]
I suggest you try to fetch smaller tiles. with 4500x4500px you are stretching the service to the very limit and I guess a problem appear in a combination of a large request and ortho.
E.g. this works:
http://services.sentinel-hub.com/ogc/wms/6a0eba64-c94f-MASKED?MAXCC=100.0&SERVICE=wms&TIME=2017-09-12T23%3A13%3A43%2F2017-09-12T23%3A13%3A43&VERSION=1.3.0&LAYERS=BANDS-S1-IW&WIDTH=450&REQUEST=GetMap&FORMAT=image%2Ftiff%3Bdepth%3D32f&HEIGHT=463&CRS=EPSG%3A4326&BBOX=33.95762,-79.69001,35.51886,-77.7672

I am therefore guessing that if you split your area in more smaller requests, e.g. 500x500 px each, it should work OK.

I will ask engineers to take a look into the error itself. It should probably not be the one you are getting...

**Comment by patrickcgray** [comment]
That does appear to be the case, I can pull a maximum of 3500x3500 successfully. Though without orthorectification 4500x4500 seems to work just fine. 

I should've done more exhaustive debugging but given that error I didn't expect it would be something on the user side. 

Thanks again @gmilcinski !
