### ISSUE TITLE
FIS Error: simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by OchiengHosea** [sentinel-hub/sentinelhub-py#72]
Code breaks at fis_request.get_data() --from the documentation examples on making FIS Requests
![error_1](https://user-images.githubusercontent.com/33859011/59158378-27f27380-8ac2-11e9-81a9-13cc6d602ec5.png)
![error2](https://user-images.githubusercontent.com/33859011/59158398-30e34500-8ac2-11e9-80fb-84f208a76024.png)

**Comment by AleksMat** [comment]
It looks that for some reason you are getting an empty payload from the service. Maybe that was some temporal problem at the service. Could you delete locally saved file `./data/fis_BANDS-S2-L1C_1.0,25.7,1.3,26.0_EPSG4326_2018-02-01T000000_2018-05-01T235959_60m__.json` and try executing the notebook again?

**Comment by AleksMat** [comment]
Closing an old issue, that probably doesn't happen anymore.
