### ISSUE TITLE
AreaSplitter tolerating multiple CRSs

### ISSUE THREAD

**Issue by wouellette** [sentinel-hub/sentinelhub-py#79]
Hi guys,

Suggesting it as an enhancement for the `areas.py` script, but having an `AreaSplitter` class which splits across UTM zones would be handy.
 
While processing very large areas going across multiple UTM zones, I realized that reprojecting everything to a single global crs, or projecting to a UTM zone for areas which stretch far west/east of the central longitudal point of that UTM zone, was causing very large inconsistencies in the sizes of the `bbox` elements, on top of forcing the resampling of Sentinel data to another crs than what it is delivered in, which brings its sets of issues too.

My idea would be to have an `AreaSplitter` that tolerates multiple CRSs, meaning that the collection of `bbox` objects it contains remain in the crs of the UTM zone it is located in. The crs information is stored at the `BBox` level currently, so one could either assign multiple CRSs to the `AreaSplitter` class, or unassign it altogether because it is redundant information to store it at both the `AreaSplitter` and `BBox` level.

Therefore, when providing the `bbox_list` elements of the `AreaSplitter` to a Sentinelhub API request (via `SentinelhubWCSInput` or any other eo-learn class requesting data), the `EOPatch` objects created could remain in their native UTM crs, and remain so until the end of the process, and a reprojection to a global crs could then be applied at the very end when the patches are brought together again.

Regards,

William

**Comment by devisperessutti** [comment]
Hi @wouellette,

Perfect timing! We wanted to write to you letting you know of the addition of two new splitters `UtmZoneSplitter` and `UtmGridSplitter`, which do exactly what you pointed out. The first one splits by UTM zone, the second one by UTM zone and MGRS tile. They are suited for large areas spanning multiple UTMs. These have been released two days ago in version 2.6.0

Please do give them a try and let us if they fulfil your requirements.

Cheers,
Devis

**Comment by wouellette** [comment]
Hi Devis,

Foolish Of me not to have taken a look at the new release... 
But hey great news! Seems to be just what I need! The consistency of bbox size globally was important to me when sizing the processing infrastructure, i.e to know that always the same amounts of pixels are ingested per splitter grid element.

Cheers,

William

**Comment by devisperessutti** [comment]
That was exactly our motivation. 

With these new splitters you will get overlapping eopatches at the border of UTM zones and UTM grid tiles, which increases the computational overhead but allows to ensure results are consistent. Information about UTM zone and MGRS row is stored in `info_list` (`.get_info_list()`)

Attached some examples of results on large countries. 

![norway_utm_grid_tiles_wgs](https://user-images.githubusercontent.com/14233816/62349684-be5e7680-b500-11e9-9c26-e5660bf2cc7e.png)

![argentina_utm_zones](https://user-images.githubusercontent.com/14233816/62349657-ae469700-b500-11e9-8cd6-eff9bc5023b1.png)

![turkey_utm_zones](https://user-images.githubusercontent.com/14233816/62349622-98d16d00-b500-11e9-8804-624fb0b37fee.png)

**Comment by AleksMat** [comment]
Closing this issue as it is probably resolved with `UtmZoneSplitter` and `UtmGridSplitter` classes.
