### ISSUE TITLE
Productinfo.json not found for image older than 2016.12

### ISSUE THREAD

**Issue by shexiaogui** [sentinel-hub/sentinelhub-py#81]
Get error when download images older than 2016.11. I tried both `safe_format=True` and `safe_format=False`. 
Does S3 bucket only contains image within certain time window?

**Comment by batic** [comment]
Could you please let us know which products specifically did you try to download?

**Comment by shexiaogui** [comment]
sure. I could list some product ids:
S2A_MSIL1C_20151128T082302_N0204_R121_T35PRM_20151128T082654
S2A_MSIL1C_20161129T081302_N0204_R078_T36PTS_20161129T082536
S2A_MSIL1C_20160307T082912_N0201_R121_T35PRP_20160307T083400

**Comment by batic** [comment]
Thanks, we’ll have a look. 

Beware that ESA changed the SAFE format structure several times, together with  file naming scheme, so that is a possible culprit.

**Comment by shexiaogui** [comment]
Is there any news on this issue ?

**Comment by AleksMat** [comment]
Unfortunately, these tiles are still missing from Sentinel-2 archive at AWS s3 bucket and they probably won't be added anytime in the future. Therefore they would have to be downloaded directly from ESA SciHub.

Closing the issue for now.
