### ISSUE TITLE
invalid syntax when running Wmsrequest

### ISSUE THREAD

**Issue by Chuan1997** [sentinel-hub/sentinelhub-py#88]
The complete code is presented as follow:
beijing_coords_wgs84 = [116.270370,39.882079,116.501942,39.964359]
beijing_bbox = BBox(bbox=beijing_coords_wgs84, crs=CRS.WGS84)

wms_true_color_request = WmsRequest(layer='TRUE-COLOR-S2-L1C',
                                    bbox=beijing_bbox,
                                    time='2017-12-15',
                                    width=512,height=856
                                    instance_id=INSTANCE_ID)
wms_true_color_img = wms_true_color_request.get_data()
print('Returned data is of type = %s and length %d.' % (type(wms_true_color_img), len(wms_true_color_img)))
print('Single element in the list is of type {} and has shape {}'.format(type(wms_true_color_img[-1]),
                                                                         wms_true_color_img[-1].shape))
plot_image(wms_true_color_img[-1])

Then a problem occured:
  File "<ipython-input-3-922d3812b6b6>", line 8
    instance_id=INSTANCE_ID)
              ^
SyntaxError: invalid syntax

**Comment by AleksMat** [comment]
Hi @Chuan1997, 

You are missing a comma at the end of line 7 in your code. Next time please double check your code before raising an issue.
