### ISSUE TITLE
Support for Sentinel-1 download from AWS into .SAFE format

### ISSUE THREAD

**Issue by knutole** [sentinel-hub/sentinelhub-py#89]
Is there planned support for downloading S1B data as SAFE files, eg. `S1B_IW_GRDH_1SDV_20180911T054651_20180911T054716_012663_0175E1_E282`? 

Would this be alot of work? I'd be happy to contribute.

**Comment by gmilcinski** [comment]
It was not on our high priority list for the moment. You are welcome to implement and do a PR/

**Comment by knutole** [comment]
I wouldn't mind looking at it. Do you have a broad idea of how it should be done? A couple of pointers would be appreciated. 💯
