### ISSUE TITLE
Error: Not a valid CRS

### ISSUE THREAD

**Issue by waleed-wajid** [sentinel-hub/sentinelhub-py#91]
Hi,
I'm using sentinelhub.BboxSplitter to split my AOI, and I have an issue with providing a coordinate reference system to the function. I get the following error:
`ValueError: CRS.from_wkt('PROJCS["GDA_1994_Albers",GEOGCS["GDA94",DATUM["Geocentric_Datum_of_Australia_1994",SPHEROID["GRS 1980",6378137,298.257222101004,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6283"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4283"]],PROJECTION["Albers_Conic_Equal_Area"],PARAMETER["latitude_of_center",0],PARAMETER["longitude_of_center",132],PARAMETER["standard_parallel_1",-18],PARAMETER["standard_parallel_2",-36],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]') is not a valid CRS`

I'm not sure what CRS the function is expecting?
I'm using version 2.6.1.

**Comment by devisperessutti** [comment]
Hello,

At the moment `sentinelhub-py` supports `WGS84`, `POP_WEB` and `UTM` coordinate systems, as described in the documentation [here](https://sentinelhub-py.readthedocs.io/en/latest/constants.html#sentinelhub.constants.CRS).

If you convert your geometry to one of the supported `CRS` it should work correctly.

**Comment by waleed-wajid** [comment]
Thanks, I was a bit slow to get that part in the documentation. I converted to UTM 55S and it works fine.
