### ISSUE TITLE
IndexError should be replaced by KeyError since it is a dict and not list.

### ISSUE THREAD

**Issue by razmikmelikbekyan** [sentinel-hub/sentinelhub-py#92]
https://github.com/sentinel-hub/sentinelhub-py/blob/1b39dd2b78836fac95f862764439101598fbf78f/sentinelhub/constants.py#L613

**Comment by AleksMat** [comment]
This has now been fixed in PR https://github.com/sentinel-hub/sentinelhub-py/pull/103. It will be released in the new version on Monday.

Thanks for letting us know about the issue.
