### ISSUE TITLE
Support for downloading granules from Google Cloud Storage (GCS)

### ISSUE THREAD

**Issue by schwehr** [sentinel-hub/sentinelhub-py#99]
Would it be possible to support downloading the data from here?

- https://cloud.google.com/storage/docs/public-datasets/sentinel-2
- https://console.cloud.google.com/storage/browser/gcp-public-data-sentinel-2
- gs://gcp-public-data-sentinel-2

**Comment by AleksMat** [comment]
We don't have any short-term plans to support download from GCS. However, we would be happy to accept any contributions regarding this.

**Comment by zigaLuksic** [comment]
Closing due to long-term inactivity
